"""Inline notebook entry points for the translator.

Two entry points, both **translation-only by default**:

- :func:`from_R`  — R source → translated Python source.
- :func:`to_R`    — Python source → translated R source.

Both return a :class:`Result` whose ``.source`` is the translated text.
Pass ``execute=True`` to also run the translation:

::

    # Translate only (default) — inspect the generated Python.
    print(hea.from_R('flights |> filter(dest == "IAH")'))

    # Translate + run. Names referenced by the translated code (here
    # ``flights``) must already exist in the caller's namespace, the same
    # as if you had written the translated Python in this cell yourself.
    flights = hea.data("flights", package="nycflights13")
    df = hea.from_R('flights |> filter(dest == "IAH")', execute=True)

The result's ``__repr__`` / ``_repr_html_`` delegate to ``.value`` when
executed (DataFrame / plot renders inline), or shows the translated
source when not.
"""

from __future__ import annotations

import ast
import inspect
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from .gaps import Gap
from .py_to_r import translate as _py_to_r
from .r_to_py import translate as _r_to_py


class HeaTranslationGap(UserWarning):
    """Warning category for gaps the translator emits during inline use.

    Each gap surfaced by :func:`from_R` or :func:`to_R` is also raised
    as one of these warnings so notebook cell output shows a visible
    breadcrumb. The same gap is appended to ``tests/parity/gaps.jsonl``
    for parity backlog tracking.
    """


@dataclass(slots=True)
class Result:
    """Outcome of a translate-and-execute call.

    - ``value``  — the value of the last top-level expression in the
      translated script. ``None`` if the script ends in a statement
      (assignment, for-loop, etc.) or has no body.
    - ``source`` — the translated source text (Python for ``from_R``,
      R for ``to_R``).
    - ``gaps``   — gaps logged during translation. Currently always
      empty (the translator's gap-emission surface is built out as
      part of the parity runner — see Phase 7).

    The ``__repr__`` and ``_repr_html_`` methods pass through to
    ``value`` so notebook cells show the DataFrame / plot directly.
    """

    value: Any = None
    source: str = ""
    gaps: list[Gap] = field(default_factory=list)

    def __repr__(self) -> str:
        # When the call was translate-only (or the script had no
        # trailing expression), show the translated source directly so
        # ``hea.from_R(...)`` in a notebook cell prints something useful.
        if self.value is None:
            return self.source.rstrip()
        return repr(self.value)

    def _repr_html_(self):  # type: ignore[override]
        """Hook used by IPython / Jupyter for rich cell output."""
        if hasattr(self.value, "_repr_html_"):
            return self.value._repr_html_()
        return None

    def _repr_png_(self):
        if hasattr(self.value, "_repr_png_"):
            return self.value._repr_png_()
        return None


def from_R(
    r_source: str,
    *,
    execute: bool = False,
    save_to: Optional[str | Path] = None,
) -> Result:
    """Translate an R snippet to Python. Returns a :class:`Result` whose
    ``.source`` holds the translated Python.

    Parameters
    ----------
    r_source
        R source code (typically a triple-quoted string in a notebook cell).
    execute
        When ``True``, run the translated Python in the caller's frame
        after translation and put the last-expression value in ``.value``.
        Names referenced by the translated code must exist in the caller's
        namespace — load datasets via ``hea.data(...)`` etc. before the
        call. Default ``False``: translate only.
    save_to
        If given, write the translated Python source to this path with a
        ``# Generated by hea.from_R`` header. Useful for promoting a
        one-off translation into a checked-in script.

    Notes
    -----
    With ``execute=True``, the script is executed against the *caller*'s
    globals + locals (merged into one namespace). Module-level callers
    (notebook cells) see assignments inside the translated script land
    in their namespace. Function-level callers do not — Python's
    ``exec`` cannot mutate a function's locals dict. The
    :attr:`Result.value` round-trips either way.
    """
    py_source = _r_to_py(r_source)

    if save_to is not None:
        _save_translated(save_to, py_source, r_source, lang="py")

    if not execute:
        return Result(value=None, source=py_source, gaps=[])

    # Capture caller frame for variable lookup.
    caller = inspect.currentframe().f_back  # type: ignore[union-attr]
    if caller is None:
        raise RuntimeError("hea.from_R could not determine caller frame")

    sentinel = f"__hea_from_r_{uuid.uuid4().hex}__"

    tree = ast.parse(py_source, "<from_R>")
    _rewrite_trailing_expr(tree, sentinel)

    exec_ns = _build_exec_namespace(caller)
    exec(compile(tree, "<from_R>", "exec"), exec_ns)
    value = exec_ns.pop(sentinel, None)
    _propagate_to_caller(caller, exec_ns)

    return Result(value=value, source=py_source, gaps=[])


def to_R(
    py_source: str,
    *,
    save_to: Optional[str | Path] = None,
    execute: bool = False,
) -> Result:
    """Translate Python source to R source.

    Parameters
    ----------
    py_source
        Python source string (typically a snippet using hea's verbs).
    save_to
        If given, write the translated R source to this path with a
        ``# Generated by hea.to_R`` header.
    execute
        When True, run the translated R via :func:`hea.translate.runner.run_r`
        (subprocess) and put the captured result frame in ``.value``.
        Default False — running R is heavy enough that you opt in.

    Returns
    -------
    Result
        ``.source`` always holds the translated R. ``.value`` is None
        unless ``execute=True``.
    """
    r_source = _py_to_r(py_source)

    if save_to is not None:
        _save_translated(save_to, r_source, py_source, lang="r")

    value: Any = None
    if execute:
        value = _execute_r_and_load(r_source)

    return Result(value=value, source=r_source, gaps=[])


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


def _rewrite_trailing_expr(tree: ast.Module, sentinel: str) -> None:
    """Mutate ``tree`` so the last top-level ``Expr`` binds its value to
    ``sentinel``. If the last statement isn't a bare expression (it's an
    assignment, for-loop, etc.), no rewrite — :attr:`Result.value` stays
    ``None`` for that script."""
    if tree.body and isinstance(tree.body[-1], ast.Expr):
        last = tree.body[-1]
        new = ast.Assign(
            targets=[ast.Name(id=sentinel, ctx=ast.Store())],
            value=last.value,
        )
        ast.copy_location(new, last)
        tree.body[-1] = new
        ast.fix_missing_locations(tree)


def _build_exec_namespace(caller) -> dict:
    """Merge caller's globals + locals + hea's public names into one dict.

    Order matters — caller globals first (broadest), then locals (most
    specific), then hea names if not already shadowed. This lets the user
    override a hea name in their own scope without surprise.

    Translated Python uses bare names (``col``, ``lit``, ``lm``, ``data``,
    ``case_when``, …) because that's how the source R script writes them.
    The top-level ``hea.*`` only exposes sub-modules now, so we pull names
    out of every user-facing sub-namespace and seed them into the exec
    namespace.
    """
    import hea  # local to avoid import-time cycles

    ns: dict = dict(caller.f_globals)
    ns.update(caller.f_locals)
    # Top-level hea attrs (the sub-modules themselves: hea.tidy, hea.models, …).
    for name in dir(hea):
        if name.startswith("_"):
            continue
        ns.setdefault(name, getattr(hea, name))
    # Names from every user-facing sub-namespace — col / lit / DataFrame /
    # lm / Binomial / anova / t_test / data / etc.
    for sub in (hea.tidy, hea.dtypes, hea.io, hea.models, hea.family,
                hea.R, hea.data, hea.session_info):
        for name in dir(sub):
            if not name.startswith("_"):
                ns.setdefault(name, getattr(sub, name))
    return ns


def _propagate_to_caller(caller, ns: dict) -> None:
    """Push assignments back into the caller's namespace, when possible.

    For module-level callers (notebook cells), ``f_locals is f_globals`` —
    we can mutate the dict directly. For function-level callers, locals
    are a snapshot the runtime won't reread; nothing we do here actually
    changes the caller's bindings.
    """
    # Don't push back hea names or dunders we added.
    import hea
    hea_names = {n for n in dir(hea) if not n.startswith("_")}
    skip = hea_names | {k for k in caller.f_globals if k.startswith("__")}
    for k, v in ns.items():
        if k in skip:
            continue
        if k not in caller.f_globals or caller.f_globals.get(k) is not v:
            caller.f_globals[k] = v


def _save_translated(
    path: str | Path,
    translated: str,
    original: str,
    *,
    lang: str,
) -> None:
    """Write the translated source with a generated-by header. ``lang`` is
    ``"py"`` or ``"r"`` and controls the comment marker."""
    path = Path(path)
    comment = "#"
    header_lines = [
        f"{comment} Generated by hea.{'from_R' if lang == 'py' else 'to_R'}",
        f"{comment} Original source:",
    ]
    for line in original.strip().splitlines():
        header_lines.append(f"{comment}   {line}")
    header = "\n".join(header_lines) + "\n\n"
    path.write_text(header + translated, encoding="utf-8")


def _execute_r_and_load(r_source: str):
    """Run translated R via the parity runner's :func:`run_r`, then read
    the captured CSV back into a hea DataFrame. Used only when the user
    asks ``to_R(..., execute=True)``."""
    import tempfile

    import polars as pl

    from .runner import run_r

    with tempfile.TemporaryDirectory(prefix="hea_to_r_") as tmpdir:
        tmp = Path(tmpdir)
        script_path = tmp / "translated.R"
        script_path.write_text(r_source, encoding="utf-8")
        result = run_r(script_path, tmp)
        if not result.ok:
            raise RuntimeError(
                f"to_R(execute=True): R subprocess failed.\n"
                f"stderr:\n{result.stderr}"
            )
        return pl.read_csv(result.out_csv)
