"""Tests for hea.translate.inline.

Most tests use module-level fixtures because Python's ``exec`` can't
mutate a function's local namespace — function-level variable assignments
inside ``from_R`` don't propagate to the test function's locals. Module
globals do work, which matches the realistic notebook-cell use case.
"""

import polars as pl
import pytest

import hea
from hea.translate.inline import from_R, to_R

flights_fixture = hea.tidy.DataFrame(
    {
        "dest": ["IAH", "JFK", "IAH", "LAX", "IAH"],
        "arr_delay": [10.0, 20.0, 15.0, 30.0, 5.0],
    }
)


class TestResult:
    def test_translate_only_by_default(self):
        r = from_R("1 + 2 * 3")
        assert r.value is None
        assert r.source.strip() == "1 + 2 * 3"
        assert r.gaps == []

    def test_repr_shows_source_when_not_executed(self):
        r = from_R("1 + 2 * 3")
        assert repr(r) == "1 + 2 * 3"

    def test_scalar_value_with_execute(self):
        r = from_R("1 + 2 * 3", execute=True)
        assert r.value == 7

    def test_string_value_with_execute(self):
        r = from_R('"hello"', execute=True)
        assert r.value == "hello"

    def test_no_trailing_expression(self):
        r = from_R("x <- 1")
        assert r.value is None
        assert r.source.strip() == "x = 1"

    def test_dataframe_value_with_execute(self):
        r = from_R("data.frame(x = c(1, 2, 3))", execute=True)
        assert isinstance(r.value, pl.DataFrame)
        assert r.value["x"].to_list() == [1, 2, 3]


class TestCallerFrame:
    """``from_R`` resolves names against the caller's globals + locals.

    These tests use ``flights_fixture`` (module-level) for the
    expression because Python's ``exec`` can read function locals but
    not bind them. Module-level names always resolve.
    """

    def test_resolves_module_global(self):
        r = from_R('flights_fixture |> filter(dest == "IAH")', execute=True)
        assert isinstance(r.value, pl.DataFrame)
        assert r.value.height == 3

    def test_full_pipeline_against_global(self):
        r = from_R(
            """
            flights_fixture |>
              filter(dest == "IAH") |>
              summarize(avg = mean(arr_delay))
        """,
            execute=True,
        )
        assert isinstance(r.value, pl.DataFrame)
        assert r.value["avg"].to_list() == [pytest.approx(10.0)]

    def test_repr_passes_through_to_value(self):
        r = from_R("data.frame(x = c(1, 2, 3))", execute=True)
        assert repr(r.value) in repr(r)

    def test_repr_html_passes_through_to_value(self):
        r = from_R("data.frame(x = c(1, 2, 3))", execute=True)
        assert r._repr_html_() is not None


class TestSaveTo:
    def test_writes_translated_python_with_header(self, tmp_path):
        path = tmp_path / "translated.py"
        from_R('flights_fixture |> filter(dest == "IAH")', save_to=path)
        content = path.read_text()
        assert "# Generated by hea.from_R" in content
        assert "# Original source:" in content
        assert content.rstrip().endswith("flights_fixture.filter(col('dest') == 'IAH')")

    def test_to_R_save_with_header(self, tmp_path):
        path = tmp_path / "out.R"
        to_R(
            'flights_fixture.filter(col("dest") == "IAH")',
            save_to=path,
        )
        content = path.read_text()
        assert "# Generated by hea.to_R" in content
        assert "|>" in content
        assert "filter(" in content


class TestToR:
    def test_basic_no_execute(self):
        r = to_R('flights.filter(col("dest") == "IAH")')
        assert r.value is None  # default: don't run R
        assert "|>" in r.source
        assert "filter(dest" in r.source

    def test_to_R_ggplot_chain(self):
        r = to_R(
            'penguins.ggplot(x="flipper_length_mm", y="body_mass_g")'
            ".geom_point().theme_minimal()"
        )
        assert "ggplot(penguins, aes(x = flipper_length_mm" in r.source
        assert "+ geom_point()" in r.source
        assert "+ theme_minimal()" in r.source

    def test_to_R_execute_round_trip(self, tmp_path):
        import shutil

        if not shutil.which("R"):
            pytest.skip("R not on PATH")
        py_source = (
            "df = hea.tidy.DataFrame({'x': [1, 2, 3, 4, 5]})\ndf.filter(col('x') > 2)\n"
        )
        r = to_R(py_source, execute=True)
        assert isinstance(r.value, pl.DataFrame)
        assert r.value.height == 3


_propagation_witness = None


class TestPropagation:
    def test_module_level_assignment_lands_in_caller_globals(self):
        from_R("propagation_witness_var <- 42L", execute=True)
        import sys

        mod = sys.modules[__name__]
        try:
            assert getattr(mod, "propagation_witness_var", None) == 42
        finally:
            if hasattr(mod, "propagation_witness_var"):
                delattr(mod, "propagation_witness_var")
