"""Tests for hea.translate.inline — Phase 9 acceptance.

Most tests use module-level fixtures because Python's ``exec`` can't
mutate a function's local namespace — function-level variable assignments
inside ``from_R`` don't propagate to the test function's locals. Module
globals do work, which matches the realistic notebook-cell use case.
"""

from pathlib import Path

import polars as pl
import pytest

import hea
from hea.translate.inline import Result, from_R, to_R


# ---------------------------------------------------------------------------
# Module-level fixtures (notebook-cell analog — top-level scope)
# ---------------------------------------------------------------------------


# These are used by the caller-frame tests below. They live at module scope
# so the exec'd translated Python can resolve them by name — same as how
# a notebook cell sees other variables in the kernel namespace.
flights_fixture = hea.tidy.DataFrame({
    "dest":      ["IAH", "JFK", "IAH", "LAX", "IAH"],
    "arr_delay": [10.0, 20.0, 15.0, 30.0, 5.0],
})


# ---------------------------------------------------------------------------
# Basic Result shape
# ---------------------------------------------------------------------------


class TestResult:
    def test_translate_only_by_default(self):
        # Default is translation-only — no execution, .value stays None.
        r = from_R("1 + 2 * 3")
        assert r.value is None
        assert r.source.strip() == "1 + 2 * 3"
        assert r.gaps == []

    def test_repr_shows_source_when_not_executed(self):
        r = from_R("1 + 2 * 3")
        assert repr(r) == "1 + 2 * 3"

    def test_scalar_value_with_execute(self):
        r = from_R("1 + 2 * 3", execute=True)
        assert r.value == 7

    def test_string_value_with_execute(self):
        r = from_R('"hello"', execute=True)
        assert r.value == "hello"

    def test_no_trailing_expression(self):
        # ``x <- 1`` is an assignment, not an expression. .value is None
        # under both execute modes; source still records the translation.
        r = from_R("x <- 1")
        assert r.value is None
        assert r.source.strip() == "x = 1"

    def test_dataframe_value_with_execute(self):
        # data.frame() literal stays self-contained.
        r = from_R("data.frame(x = c(1, 2, 3))", execute=True)
        assert isinstance(r.value, pl.DataFrame)
        assert r.value["x"].to_list() == [1, 2, 3]


# ---------------------------------------------------------------------------
# Caller-frame variable resolution
# ---------------------------------------------------------------------------


class TestCallerFrame:
    """``from_R`` resolves names against the caller's globals + locals.

    These tests use ``flights_fixture`` (module-level) for the
    expression because Python's ``exec`` can read function locals but
    not bind them. Module-level names always resolve.
    """

    def test_resolves_module_global(self):
        r = from_R('flights_fixture |> filter(dest == "IAH")', execute=True)
        assert isinstance(r.value, pl.DataFrame)
        assert r.value.height == 3

    def test_full_pipeline_against_global(self):
        r = from_R("""
            flights_fixture |>
              filter(dest == "IAH") |>
              summarize(avg = mean(arr_delay))
        """, execute=True)
        assert isinstance(r.value, pl.DataFrame)
        assert r.value["avg"].to_list() == [pytest.approx(10.0)]

    def test_repr_passes_through_to_value(self):
        # The Result's ``__repr__`` delegates to the value's repr so
        # notebook cell output renders DataFrames as tables.
        r = from_R("data.frame(x = c(1, 2, 3))", execute=True)
        assert repr(r.value) in repr(r)

    def test_repr_html_passes_through_to_value(self):
        r = from_R("data.frame(x = c(1, 2, 3))", execute=True)
        # polars DataFrames implement _repr_html_; the Result must too.
        assert r._repr_html_() is not None


# ---------------------------------------------------------------------------
# save_to
# ---------------------------------------------------------------------------


class TestSaveTo:
    def test_writes_translated_python_with_header(self, tmp_path):
        path = tmp_path / "translated.py"
        from_R('flights_fixture |> filter(dest == "IAH")', save_to=path)
        content = path.read_text()
        assert "# Generated by hea.from_R" in content
        assert "# Original source:" in content
        # The translated Python should be at the bottom of the file.
        assert content.rstrip().endswith(
            "flights_fixture.filter(col('dest') == 'IAH')"
        )

    def test_to_R_save_with_header(self, tmp_path):
        path = tmp_path / "out.R"
        to_R(
            'flights_fixture.filter(col("dest") == "IAH")',
            save_to=path,
        )
        content = path.read_text()
        assert "# Generated by hea.to_R" in content
        # The translated R should include the dplyr pipe form.
        assert "|>" in content
        assert "filter(" in content


# ---------------------------------------------------------------------------
# to_R direction
# ---------------------------------------------------------------------------


class TestToR:
    def test_basic_no_execute(self):
        r = to_R('flights.filter(col("dest") == "IAH")')
        assert r.value is None  # default: don't run R
        assert "|>" in r.source
        assert "filter(dest" in r.source

    def test_to_R_ggplot_chain(self):
        r = to_R(
            'penguins.ggplot(x="flipper_length_mm", y="body_mass_g")'
            '.geom_point().theme_minimal()'
        )
        assert "ggplot(penguins, aes(x = flipper_length_mm" in r.source
        assert "+ geom_point()" in r.source
        assert "+ theme_minimal()" in r.source

    def test_to_R_execute_round_trip(self, tmp_path):
        # Skip if R isn't available — same gate as the runner tests.
        import shutil
        if not shutil.which("R"):
            pytest.skip("R not on PATH")
        # Only translator-recognized constructs in the source — no
        # ``import hea`` (out of scope; py_to_r doesn't translate imports).
        py_source = (
            "df = hea.tidy.DataFrame({'x': [1, 2, 3, 4, 5]})\n"
            "df.filter(col('x') > 2)\n"
        )
        r = to_R(py_source, execute=True)
        assert isinstance(r.value, pl.DataFrame)
        assert r.value.height == 3


# ---------------------------------------------------------------------------
# Side-effect propagation back to caller
# ---------------------------------------------------------------------------


# Module-level state lets us observe propagation reliably.
_propagation_witness = None


class TestPropagation:
    def test_module_level_assignment_lands_in_caller_globals(self):
        # ``from_R`` executes the rewritten Python in a namespace that
        # includes the caller's globals; assignments inside the snippet
        # write to that dict, and we copy back to caller.f_globals.
        from_R("propagation_witness_var <- 42L", execute=True)
        # The witness lands in this module's globals (caller frame).
        import sys
        mod = sys.modules[__name__]
        try:
            assert getattr(mod, "propagation_witness_var", None) == 42
        finally:
            if hasattr(mod, "propagation_witness_var"):
                delattr(mod, "propagation_witness_var")
