"""End-to-end tests for ``hea.bam``.

Sections (top → bottom):

1. **predict-API** (Phase 4.0 of bam-port plan): pin
   ``predict(newdata=None)`` for every (type, se_fit) combo on
   Gaussian-identity, PIRLS, and discrete bam fits. The inherited
   ``gam.predict`` shape-clashes against ``_offset`` because every bam
   path stores ``self._X_full = qr.R`` (p × p); the override at
   ``hea/bam.py:2049`` covers the no-newdata case via cached arrays
   plus chunked walks.

2. **chicago oracle** (Phase 3 of plan): two Poisson fits against
   ``mgcv::bam(discrete=TRUE)``. ``simple`` exercises the multi-smooth
   non-matrix path; ``lag`` exercises the matrix-arg ``compress_df``
   shuffle/pad that Phase 1 fixed and the POI optimiser from Phase 2′.

3. **small_data oracle** (Phase 1 + Phase 2′): the rank-deficient
   Poisson ``te(pm10, lag, k=c(5, 3))`` toy. Force-sp matches mgcv at
   ≤ 1e-9; auto-sp lands in a different specific point of the flat
   REML basin so we only assert ≤ 1e-5 on fitted (gauge-invariant).
   Coefs are NOT element-wise checked — pivoted Cholesky picks
   different drop positions than mgcv's gauge.

Family-specific bam parity (``Scat`` etc.) lives in ``test_family.py``
beside the family unit tests. Oracles generated by
``tests/r_oracle/dump_bam_*.R``; raw fixtures live under
``tests/fixtures/``. Each test ``skipif`` s when its oracle is absent
so the file runs cleanly without an mgcv installation.
"""
from pathlib import Path

import numpy as np
import polars as pl
import pytest

from hea.family import Poisson
import hea


# =============================================================================
# 1. predict-API regression (Phase 4.0)
# =============================================================================

def _gauss_data(n: int = 200, seed: int = 0) -> pl.DataFrame:
    rng = np.random.default_rng(seed)
    return pl.DataFrame({
        "x": rng.uniform(0.0, 1.0, n),
        "y": rng.normal(0.0, 1.0, n),
    })


def _poisson_data(n: int = 200, seed: int = 0) -> pl.DataFrame:
    rng = np.random.default_rng(seed)
    eta = 0.5 + rng.uniform(0.0, 1.0, n)
    return pl.DataFrame({
        "x": rng.uniform(0.0, 1.0, n),
        "y": rng.poisson(np.exp(eta)),
    })


def _check_predict_no_newdata(m):
    n = m.n
    p = m.p
    fitted = m.fitted_values
    eta_full = m.linear_predictors

    # response / link / lpmatrix without se_fit
    assert np.allclose(m.predict(), fitted, rtol=0, atol=0)
    assert np.allclose(m.predict(type="link"), eta_full, rtol=0, atol=0)
    X = m.predict(type="lpmatrix")
    assert X.shape == (n, p)

    # se_fit on response and link returns 2-tuples of length-n
    fit, se = m.predict(se_fit=True)
    assert fit.shape == (n,)
    assert se.shape == (n,)
    assert np.all(np.isfinite(se))
    assert np.all(se >= 0.0)
    assert np.allclose(fit, fitted, rtol=0, atol=0)

    fit_l, se_l = m.predict(type="link", se_fit=True)
    assert np.allclose(fit_l, eta_full, rtol=0, atol=0)
    assert se_l.shape == (n,)
    assert np.all(np.isfinite(se_l))

    # extra offset shifts link by exactly that amount
    extra = np.full(n, 0.123)
    eta_extra = m.predict(type="link", offset=extra)
    assert np.allclose(eta_extra - eta_full, extra)


def test_predict_gaussian_identity():
    m = hea.bam("y ~ s(x, k=5)", _gauss_data())
    _check_predict_no_newdata(m)


def test_predict_poisson_pirls():
    m = hea.bam("y ~ s(x, k=5)", _poisson_data(), family=Poisson())
    _check_predict_no_newdata(m)


def test_predict_poisson_discrete():
    m = hea.bam("y ~ s(x, k=5)", _poisson_data(),
                family=Poisson(), discrete=True)
    _check_predict_no_newdata(m)


def test_predict_newdata_matches_in_sample():
    """``predict(newdata=df)`` agrees with cached fitted_values when df
    is the training frame — sanity-check the super().predict delegation."""
    df = _poisson_data()
    m = hea.bam("y ~ s(x, k=5)", df, family=Poisson(), discrete=True)
    yhat = m.predict(newdata=df)
    assert np.allclose(yhat, m.fitted_values, rtol=1e-12, atol=1e-12)


def test_predict_lpmatrix_invalid_with_se():
    m = hea.bam("y ~ s(x, k=5)", _gauss_data())
    with pytest.raises(ValueError, match="se_fit=True is not allowed"):
        m.predict(type="lpmatrix", se_fit=True)


def test_predict_unknown_type():
    m = hea.bam("y ~ s(x, k=5)", _gauss_data())
    with pytest.raises(ValueError, match="type must be"):
        m.predict(type="bogus")


# =============================================================================
# 2. chicago oracle (Phase 3)
# =============================================================================

_CHICAGO = Path(__file__).parent / "fixtures" / "chicago"


def _load_chicago():
    return pl.read_csv(str(_CHICAGO / "data.csv"))


def _to_dat(df: pl.DataFrame) -> dict:
    return {col: df[col].to_numpy().astype(float) for col in df.columns}


@pytest.mark.skipif(
    not (_CHICAGO / "data.csv").exists(),
    reason="chicago oracle missing — run tests/r_oracle/dump_bam_chicago.R",
)
def test_chicago_simple():
    """5-smooth Poisson on chicago, no matrix args."""
    dat = _to_dat(_load_chicago())
    m = hea.bam(
        "death ~ s(time, k=200) + s(pm10median) + s(o3median) + "
        "s(so2median) + s(tmpd)",
        dat, family=Poisson(), discrete=True,
    )
    fit_mgcv = np.loadtxt(_CHICAGO / "simple" / "fitted.csv")
    fit_hea = np.asarray(m.fitted_values)
    rel_fit = float(
        np.linalg.norm(fit_hea - fit_mgcv) / np.linalg.norm(fit_mgcv)
    )
    assert rel_fit < 1e-5, (
        f"chicago simple fitted rel diff {rel_fit:.3e} > 1e-5"
    )

    sp_mgcv = np.atleast_1d(np.loadtxt(_CHICAGO / "simple" / "sp.csv"))
    sp_hea = np.asarray(m.sp)
    log_sp_diff = np.abs(np.log(sp_hea) - np.log(sp_mgcv))
    # 15× upper bound covers the flat-basin sp ambiguity (log15 ≈ 2.7).
    # Tighten only after Phase 2′.7 (POI optimizer) lands.
    assert float(log_sp_diff.max()) < 3.0, (
        f"chicago simple sp out of basin: hea={sp_hea}, mgcv={sp_mgcv}"
    )


@pytest.mark.skipif(
    not (_CHICAGO / "data.csv").exists(),
    reason="chicago oracle missing — run tests/r_oracle/dump_bam_chicago.R",
)
def test_chicago_lag():
    """Distributed-lag matrix-arg te() on chicago — exercises the
    matrix-arg ``compress_df`` shuffle / pad path that Phase 1 fixed."""
    dat = _to_dat(_load_chicago())

    # Build the lag matrix (exact mirror of dump_bam_chicago.R::lagard).
    def lagard(x, n_lag=6):
        n = len(x)
        X = np.full((n, n_lag), np.nan)
        for i in range(1, n_lag + 1):
            X[i - 1: n, i - 1] = x[: n - i + 1]
        return X

    pm10_lag = lagard(dat["pm10median"], n_lag=6)
    n = len(dat["pm10median"])
    lag_idx = np.tile(np.arange(6, dtype=float), (n, 1))
    good = ~np.any(np.isnan(pm10_lag), axis=1)
    dat2 = {k: v[good] for k, v in dat.items()}
    dat2["pm10_lag"] = pm10_lag[good]
    dat2["lag_idx"] = lag_idx[good]

    m = hea.bam(
        "death ~ s(time, k=200) + te(pm10_lag, lag_idx, k=c(10, 5)) "
        "+ s(tmpd)",
        dat2, family=Poisson(), discrete=True,
    )
    fit_mgcv = np.loadtxt(_CHICAGO / "lag" / "fitted.csv")
    fit_hea = np.asarray(m.fitted_values)
    rel_fit = float(
        np.linalg.norm(fit_hea - fit_mgcv) / np.linalg.norm(fit_mgcv)
    )
    # POI optimizer brings chicago lag to ~5e-9 on fitted; tightened
    # from the original 1e-2 bound so future regressions are caught.
    assert rel_fit < 1e-7, (
        f"chicago lag fitted rel diff {rel_fit:.3e} > 1e-7"
    )

    sp_mgcv = np.atleast_1d(np.loadtxt(_CHICAGO / "lag" / "sp.csv"))
    sp_hea = np.asarray(m.sp)
    log_sp_diff = np.abs(np.log(sp_hea) - np.log(sp_mgcv))
    # POI lands on the same minimum as mgcv to 7 significant digits on
    # chicago lag — tighten the bound so a regression flips this test.
    assert float(log_sp_diff.max()) < 1e-4, (
        f"chicago lag sp out of basin: hea={sp_hea}, mgcv={sp_mgcv}"
    )


# =============================================================================
# 3. small_data oracle (Phase 1 + Phase 2′)
# =============================================================================

_SMALL = Path(__file__).parent / "fixtures" / "small_data"


def _load_small_dat():
    df = pl.read_csv(str(_SMALL / "data.csv"))
    pm10 = df.select(["X1", "X2", "X3", "X4"]).to_numpy().astype(float)
    lag = df.select(["X1.1", "X2.1", "X3.1", "X4.1"]).to_numpy().astype(float)
    return {"y": df["y"].to_numpy().astype(float),
            "pm10": pm10, "lag": lag}


@pytest.mark.skipif(
    not (_SMALL / "data.csv").exists(),
    reason="small_data oracle missing — see tests/r_oracle/",
)
def test_small_data_force_sp():
    """With mgcv's sp forced, hea's β must give fitted matching mgcv
    to ≤ 1e-9 (gauge-invariant predictive equivalence)."""
    dat = _load_small_dat()
    sp_mgcv = np.atleast_1d(np.loadtxt(_SMALL / "sp.csv"))
    m = hea.bam("y ~ te(pm10, lag, k=c(5, 3))", dat,
                family=Poisson(), discrete=True, sp=sp_mgcv)

    fit_mgcv = np.loadtxt(_SMALL / "fitted.csv")
    fit_hea = np.asarray(m.fitted_values)
    rel_fit = float(
        np.linalg.norm(fit_hea - fit_mgcv) / np.linalg.norm(fit_mgcv)
    )
    assert rel_fit < 1e-9, (
        f"small_data force-sp fitted rel diff {rel_fit:.3e} > 1e-9"
    )


@pytest.mark.skipif(
    not (_SMALL / "data.csv").exists(),
    reason="small_data oracle missing",
)
def test_small_data_auto_sp():
    """Auto-sp on the rank-deficient small_data model lands in a
    different specific basin point than mgcv, but fitted should still
    be within 1e-5 because the basin is flat and both impls minimise
    REML to machine precision."""
    dat = _load_small_dat()
    m = hea.bam("y ~ te(pm10, lag, k=c(5, 3))", dat,
                family=Poisson(), discrete=True)

    fit_mgcv = np.loadtxt(_SMALL / "fitted.csv")
    fit_hea = np.asarray(m.fitted_values)
    rel_fit = float(
        np.linalg.norm(fit_hea - fit_mgcv) / np.linalg.norm(fit_mgcv)
    )
    assert rel_fit < 1e-5, (
        f"small_data auto-sp fitted rel diff {rel_fit:.3e} > 1e-5"
    )


