"""Unit-level oracle parity for ``hea.family.Scat``.

Pins ``Scat.Dd`` levels 0/1/2, ``Scat.ls_extended``, ``Scat.dev_resids``,
``Scat.aic``, and ``Scat.preinitialize`` against a frozen mgcv oracle
generated by ``tests/r_oracle/dump_scat_unit.R``.

The pin is per-element to ≤ 5e-13 — well inside double-precision
roundoff for the cumulative formulas in ``Dd`` level 2, which exercises
products of up to four ν-, σ- and (y-μ)-dependent quantities.
"""
from pathlib import Path

import numpy as np
import polars as pl
import pytest

from hea.family import Scat


_FIX = Path(__file__).parent / "fixtures" / "scat_unit"


def _have_fixtures() -> bool:
    return all((_FIX / f).exists() for f in (
        "inputs.csv", "theta.csv", "dd_lvl0.csv", "dd_lvl1.csv",
        "dd_lvl2.csv", "ls_summary.csv", "LSTH1.csv", "dev.csv",
        "aic.csv", "preinit.csv",
    ))


pytestmark = pytest.mark.skipif(
    not _have_fixtures(),
    reason="scat oracle missing — run tests/r_oracle/dump_scat_unit.R",
)


def _load_inputs():
    df = pl.read_csv(str(_FIX / "inputs.csv"))
    y = df["y"].to_numpy().astype(float)
    mu = df["mu"].to_numpy().astype(float)
    wt = df["wt"].to_numpy().astype(float)
    theta = np.atleast_1d(np.loadtxt(_FIX / "theta.csv"))
    return y, mu, wt, theta


def _scat():
    s = Scat(min_df=5)
    _, _, _, theta = _load_inputs()
    s.set_theta(theta)
    return s


def test_scat_dd_level0():
    y, mu, wt, theta = _load_inputs()
    s = _scat()
    dd = s.Dd(y, mu, theta, wt, level=0)
    oracle = pl.read_csv(str(_FIX / "dd_lvl0.csv")).to_numpy()
    assert np.max(np.abs(dd["Dmu"] - oracle[:, 0])) < 5e-13
    assert np.max(np.abs(dd["Dmu2"] - oracle[:, 1])) < 5e-13
    assert np.max(np.abs(dd["EDmu2"] - oracle[:, 2])) < 5e-13


def test_scat_dd_level1():
    y, mu, wt, theta = _load_inputs()
    s = _scat()
    dd = s.Dd(y, mu, theta, wt, level=1)
    oracle = pl.read_csv(str(_FIX / "dd_lvl1.csv")).to_numpy()
    pairs = [
        (dd["Dth"][:, 0],     oracle[:, 0]),
        (dd["Dth"][:, 1],     oracle[:, 1]),
        (dd["Dmuth"][:, 0],   oracle[:, 2]),
        (dd["Dmuth"][:, 1],   oracle[:, 3]),
        (dd["Dmu2th"][:, 0],  oracle[:, 4]),
        (dd["Dmu2th"][:, 1],  oracle[:, 5]),
        (dd["EDmu2th"][:, 0], oracle[:, 6]),
        (dd["EDmu2th"][:, 1], oracle[:, 7]),
        (dd["Dmu3"],          oracle[:, 8]),
        (dd["EDmu3"],         oracle[:, 9]),
    ]
    err = max(float(np.max(np.abs(h - m))) for h, m in pairs)
    assert err < 5e-13, f"Dd level 1 max abs err {err:.3e}"


def test_scat_dd_level2():
    y, mu, wt, theta = _load_inputs()
    s = _scat()
    dd = s.Dd(y, mu, theta, wt, level=2)
    oracle = pl.read_csv(str(_FIX / "dd_lvl2.csv")).to_numpy()
    pairs = [
        (dd["Dmu4"],          oracle[:, 0]),
        (dd["Dmu3th"][:, 0],  oracle[:, 1]),
        (dd["Dmu3th"][:, 1],  oracle[:, 2]),
        (dd["Dmu2th2"][:, 0], oracle[:, 3]),
        (dd["Dmu2th2"][:, 1], oracle[:, 4]),
        (dd["Dmu2th2"][:, 2], oracle[:, 5]),
        (dd["Dmuth2"][:, 0],  oracle[:, 6]),
        (dd["Dmuth2"][:, 1],  oracle[:, 7]),
        (dd["Dmuth2"][:, 2],  oracle[:, 8]),
        (dd["Dth2"][:, 0],    oracle[:, 9]),
        (dd["Dth2"][:, 1],    oracle[:, 10]),
        (dd["Dth2"][:, 2],    oracle[:, 11]),
    ]
    err = max(float(np.max(np.abs(h - m))) for h, m in pairs)
    assert err < 5e-13, f"Dd level 2 max abs err {err:.3e}"


def test_scat_ls_extended():
    y, mu, wt, theta = _load_inputs()
    s = _scat()
    ls = s.ls_extended(y, wt, theta=theta, scale=1.0)
    summary = np.atleast_1d(np.loadtxt(_FIX / "ls_summary.csv"))
    assert abs(ls["ls"] - summary[0]) < 5e-13
    assert abs(ls["lsth1"][0] - summary[1]) < 5e-13
    assert abs(ls["lsth1"][1] - summary[2]) < 5e-13
    assert abs(ls["lsth2"][0, 0] - summary[3]) < 5e-13
    LSTH1 = pl.read_csv(str(_FIX / "LSTH1.csv")).to_numpy()
    assert np.max(np.abs(ls["LSTH1"] - LSTH1)) < 5e-13


def test_scat_dev_resids():
    y, mu, wt, theta = _load_inputs()
    s = _scat()
    dev_h = s.dev_resids(y, mu, wt, theta=theta)
    dev_o = pl.read_csv(str(_FIX / "dev.csv")).to_numpy().ravel()
    assert np.max(np.abs(dev_h - dev_o)) < 5e-13


def test_scat_aic():
    y, mu, wt, theta = _load_inputs()
    s = _scat()
    aic_h = s.aic(y, mu, dev=None, wt=wt, n=len(y), theta=theta)
    aic_o = float(np.atleast_1d(np.loadtxt(_FIX / "aic.csv"))[0])
    assert abs(aic_h - aic_o) < 5e-13


def test_scat_preinitialize():
    y, _, _, _ = _load_inputs()
    s = Scat(min_df=5)   # n_theta=2 → preinit returns Theta
    pini = s.preinitialize(y)
    assert pini is not None and "Theta" in pini
    pini_o = np.atleast_1d(np.loadtxt(_FIX / "preinit.csv"))
    assert np.max(np.abs(pini["Theta"] - pini_o)) < 5e-13


def test_scat_preinitialize_locked():
    """When user supplies both θ as positive (n_theta=0), preinit
    returns ``None`` so the constructor's iniTheta is used unchanged."""
    s = Scat(theta=(7.0, 0.5), min_df=5)
    assert s.n_theta == 0
    assert s.preinitialize(np.array([1.0, 2.0, 3.0])) is None


def test_scat_get_set_theta_roundtrip():
    s = Scat(min_df=5)
    s.set_theta([0.4, -0.3])
    assert np.allclose(s.get_theta(trans=False), [0.4, -0.3])
    nu, sig = s.get_theta(trans=True)
    assert nu == pytest.approx(np.exp(0.4) + 5.0)
    assert sig == pytest.approx(np.exp(-0.3))


def test_scat_link_validation():
    Scat(link="identity")
    Scat(link="log")
    Scat(link="inverse")
    with pytest.raises(ValueError, match="not available for scat"):
        Scat(link="probit")


# ---------- _estimate_theta vs mgcv estimate.theta -------------------------

_ETH = Path(__file__).parent / "fixtures" / "scat_estth"


@pytest.mark.skipif(
    not (_ETH / "inputs.csv").exists(),
    reason="scat estimate.theta oracle missing — run "
           "tests/r_oracle/dump_scat_estth.R",
)
@pytest.mark.parametrize("init_name", ["near", "far"])
def test_scat_estimate_theta(init_name: str):
    """mgcv ``estimate.theta`` parity for ``_estimate_theta`` on a
    Scat family with heavy-tailed residuals (so ν stays finite and
    both impls converge to a well-defined optimum)."""
    from hea.bam import _estimate_theta
    df = pl.read_csv(str(_ETH / "inputs.csv"))
    y = df["y"].to_numpy().astype(float)
    mu = df["mu"].to_numpy().astype(float)
    th0 = np.atleast_1d(np.loadtxt(_ETH / f"{init_name}_init.csv"))
    th_oracle = np.atleast_1d(np.loadtxt(_ETH / f"{init_name}_out.csv"))

    s = Scat(min_df=4)
    s.set_theta(th0)
    th_h = _estimate_theta(s, y, mu, scale=1.0, wt=np.ones(len(y)),
                           tol=1e-7)
    err = float(np.max(np.abs(th_h - th_oracle)))
    assert err < 1e-12, (
        f"{init_name}-init: hea={th_h}, mgcv={th_oracle}, err={err:.3e}"
    )
