"""Chicago air-pollution oracle parity test for ``hea.bam(discrete=True)``.

Two fits, both Poisson:

* ``simple`` — multi-smooth ``s()`` only, exercises non-matrix discrete path.
* ``lag``    — distributed-lag matrix-arg ``te()``, exercises the
  matrix-arg discrete path that the Phase 1 RNG fix targets.

Oracle generated by ``tests/r_oracle/dump_bam_chicago.R``; raw fixtures
under ``tests/fixtures/chicago/``.

Tolerances reflect the rank-deficiency reality documented in the
bam-port plan:

* ``fitted`` is gauge-invariant and matches at machine precision (≤ 1e-6
  on simple, ≤ 1e-2 on lag — the lag fit's outer optimiser converges to
  a slightly different sp than mgcv's, leaving a residual fit gap).
* ``coef`` matches in row-sum / column-space identities, NOT element-
  wise: rank-deficient null directions take different specific values
  in hea's vs mgcv's pivoted Cholesky gauge. We do not assert
  element-wise coef equality.
* ``sp`` matches to within 15× on each entry — the auto-sp basin is
  flat for these models and both impls land at near-identical REML
  scores at different sp values.
"""
from pathlib import Path

import numpy as np
import polars as pl
import pytest

from hea.family import Poisson
import hea


_FIX = Path(__file__).parent / "fixtures" / "chicago"


def _load_data():
    return pl.read_csv(str(_FIX / "data.csv"))


def _to_dat(df: pl.DataFrame) -> dict:
    return {col: df[col].to_numpy().astype(float) for col in df.columns}


@pytest.mark.skipif(
    not (_FIX / "data.csv").exists(),
    reason="chicago oracle missing — run tests/r_oracle/dump_bam_chicago.R",
)
def test_chicago_simple():
    """5-smooth Poisson on chicago, no matrix args."""
    df = _load_data()
    dat = _to_dat(df)
    m = hea.bam(
        "death ~ s(time, k=200) + s(pm10median) + s(o3median) + "
        "s(so2median) + s(tmpd)",
        dat, family=Poisson(), discrete=True,
    )
    fit_mgcv = np.loadtxt(_FIX / "simple" / "fitted.csv")
    fit_hea = np.asarray(m.fitted_values)
    rel_fit = float(np.linalg.norm(fit_hea - fit_mgcv)
                    / np.linalg.norm(fit_mgcv))
    assert rel_fit < 1e-5, (
        f"chicago simple fitted rel diff {rel_fit:.3e} > 1e-5"
    )

    sp_mgcv = np.atleast_1d(np.loadtxt(_FIX / "simple" / "sp.csv"))
    sp_hea = np.asarray(m.sp)
    log_sp_diff = np.abs(np.log(sp_hea) - np.log(sp_mgcv))
    # 15× upper bound covers the flat-basin sp ambiguity (log15 ≈ 2.7).
    # Tighten only after Phase 2′.7 (POI optimizer) lands.
    assert float(log_sp_diff.max()) < 3.0, (
        f"chicago simple sp out of basin: hea={sp_hea}, mgcv={sp_mgcv}"
    )


@pytest.mark.skipif(
    not (_FIX / "data.csv").exists(),
    reason="chicago oracle missing — run tests/r_oracle/dump_bam_chicago.R",
)
def test_chicago_lag():
    """Distributed-lag matrix-arg te() on chicago — exercises the
    matrix-arg ``compress_df`` shuffle / pad path that Phase 1 fixed."""
    df = _load_data()
    dat = _to_dat(df)

    # Build the lag matrix (exact mirror of dump_bam_chicago.R::lagard).
    def lagard(x, n_lag=6):
        n = len(x)
        X = np.full((n, n_lag), np.nan)
        for i in range(1, n_lag + 1):
            X[i - 1: n, i - 1] = x[: n - i + 1]
        return X

    pm10_lag = lagard(dat["pm10median"], n_lag=6)
    n = len(dat["pm10median"])
    lag_idx = np.tile(np.arange(6, dtype=float), (n, 1))
    good = ~np.any(np.isnan(pm10_lag), axis=1)
    dat2 = {k: v[good] for k, v in dat.items()}
    dat2["pm10_lag"] = pm10_lag[good]
    dat2["lag_idx"] = lag_idx[good]

    m = hea.bam(
        "death ~ s(time, k=200) + te(pm10_lag, lag_idx, k=c(10, 5)) "
        "+ s(tmpd)",
        dat2, family=Poisson(), discrete=True,
    )
    fit_mgcv = np.loadtxt(_FIX / "lag" / "fitted.csv")
    fit_hea = np.asarray(m.fitted_values)
    rel_fit = float(np.linalg.norm(fit_hea - fit_mgcv)
                    / np.linalg.norm(fit_mgcv))
    assert rel_fit < 1e-2, (
        f"chicago lag fitted rel diff {rel_fit:.3e} > 1e-2"
    )

    sp_mgcv = np.atleast_1d(np.loadtxt(_FIX / "lag" / "sp.csv"))
    sp_hea = np.asarray(m.sp)
    log_sp_diff = np.abs(np.log(sp_hea) - np.log(sp_mgcv))
    assert float(log_sp_diff.max()) < 3.0, (
        f"chicago lag sp out of basin: hea={sp_hea}, mgcv={sp_mgcv}"
    )
