"""End-to-end tests for ``hea.bam``.

Sections (top → bottom):

1. **predict-API** (Phase 4.0 of bam-port plan): pin
   ``predict(newdata=None)`` for every (type, se_fit) combo on
   Gaussian-identity, PIRLS, and discrete bam fits. The inherited
   ``gam.predict`` shape-clashes against ``_offset`` because every bam
   path stores ``self._X_full = qr.R`` (p × p); the override at
   ``hea/bam.py:2049`` covers the no-newdata case via cached arrays
   plus chunked walks.

2. **chicago oracle** (Phase 3 of plan): two Poisson fits against
   ``mgcv::bam(discrete=TRUE)``. ``simple`` exercises the multi-smooth
   non-matrix path; ``lag`` exercises the matrix-arg ``compress_df``
   shuffle/pad that Phase 1 fixed and the POI optimiser from Phase 2′.

3. **small_data oracle** (Phase 1 + Phase 2′): the rank-deficient
   Poisson ``te(pm10, lag, k=c(5, 3))`` toy. Force-sp matches mgcv at
   ≤ 1e-9; auto-sp lands in a different specific point of the flat
   REML basin so we only assert ≤ 1e-5 on fitted (gauge-invariant).
   Coefs are NOT element-wise checked — pivoted Cholesky picks
   different drop positions than mgcv's gauge.

4. **summary()/rank parity** (plan items P1, P5): the inherited
   ``summary()`` used to raise ``AttributeError: _se_report`` on every
   bam, and ``m.rank`` was never set — neither was exercised by the
   predict/oracle sections above. Pins the summary.gam tables + rank on
   Gaussian, Poisson, and a rank-deficient fit.

Family-specific bam parity (``Scat`` etc.) lives in ``test_family.py``
beside the family unit tests. Oracles generated by
``tests/r_oracle/dump_bam_*.R``; raw fixtures live under
``tests/fixtures/``. Each test ``skipif`` s when its oracle is absent
so the file runs cleanly without an mgcv installation.
"""
import csv
import io
from contextlib import redirect_stdout
from pathlib import Path

import numpy as np
import polars as pl
import pytest

from hea.family import Poisson
import hea


# =============================================================================
# 1. predict-API regression (Phase 4.0)
# =============================================================================

def _gauss_data(n: int = 200, seed: int = 0) -> pl.DataFrame:
    rng = np.random.default_rng(seed)
    return pl.DataFrame({
        "x": rng.uniform(0.0, 1.0, n),
        "y": rng.normal(0.0, 1.0, n),
    })


def _poisson_data(n: int = 200, seed: int = 0) -> pl.DataFrame:
    rng = np.random.default_rng(seed)
    eta = 0.5 + rng.uniform(0.0, 1.0, n)
    return pl.DataFrame({
        "x": rng.uniform(0.0, 1.0, n),
        "y": rng.poisson(np.exp(eta)),
    })


def _check_predict_no_newdata(m):
    n = m.n
    p = m.p
    fitted = m.fitted_values
    eta_full = m.linear_predictors

    # response / link return a DataFrame with column "fit".
    assert np.allclose(m.predict()["fit"].to_numpy(), fitted, rtol=0, atol=0)
    assert np.allclose(
        m.predict(type="link")["fit"].to_numpy(), eta_full, rtol=0, atol=0,
    )
    # lpmatrix is the raw design matrix (ndarray), not a prediction.
    X = m.predict(type="lpmatrix")
    assert X.shape == (n, p)

    # se_fit adds a second column "se.fit".
    pred = m.predict(se_fit=True)
    fit = pred["fit"].to_numpy()
    se = pred["se.fit"].to_numpy()
    assert fit.shape == (n,)
    assert se.shape == (n,)
    assert np.all(np.isfinite(se))
    assert np.all(se >= 0.0)
    assert np.allclose(fit, fitted, rtol=0, atol=0)

    pred_l = m.predict(type="link", se_fit=True)
    fit_l = pred_l["fit"].to_numpy()
    se_l = pred_l["se.fit"].to_numpy()
    assert np.allclose(fit_l, eta_full, rtol=0, atol=0)
    assert se_l.shape == (n,)
    assert np.all(np.isfinite(se_l))

    # extra offset shifts link by exactly that amount
    extra = np.full(n, 0.123)
    eta_extra = m.predict(type="link", offset=extra)["fit"].to_numpy()
    assert np.allclose(eta_extra - eta_full, extra)


def test_predict_gaussian_identity():
    m = hea.models.bam("y ~ s(x, k=5)", _gauss_data())
    _check_predict_no_newdata(m)


def test_predict_poisson_pirls():
    m = hea.models.bam("y ~ s(x, k=5)", _poisson_data(), family=Poisson())
    _check_predict_no_newdata(m)


def test_predict_poisson_discrete():
    m = hea.models.bam("y ~ s(x, k=5)", _poisson_data(),
                family=Poisson(), discrete=True)
    _check_predict_no_newdata(m)


def test_predict_newdata_matches_in_sample():
    """``predict(newdata=df)`` agrees with cached fitted_values when df
    is the training frame — sanity-check the super().predict delegation."""
    df = _poisson_data()
    m = hea.models.bam("y ~ s(x, k=5)", df, family=Poisson(), discrete=True)
    yhat = m.predict(newdata=df)["fit"].to_numpy()
    assert np.allclose(yhat, m.fitted_values, rtol=1e-12, atol=1e-12)


def test_predict_lpmatrix_invalid_with_se():
    m = hea.models.bam("y ~ s(x, k=5)", _gauss_data())
    with pytest.raises(ValueError, match="se_fit=True is not allowed"):
        m.predict(type="lpmatrix", se_fit=True)


def test_predict_unknown_type():
    m = hea.models.bam("y ~ s(x, k=5)", _gauss_data())
    with pytest.raises(ValueError, match="type must be"):
        m.predict(type="bogus")


# =============================================================================
# 1b. predict surface parity — P4 (terms / iterms / exclude / unconditional)
# =============================================================================

_BAM_PREDICT = Path(__file__).parent / "fixtures" / "bam_predict"
_BAM_SUMMARY = Path(__file__).parent / "fixtures" / "bam_summary"


@pytest.mark.skipif(
    not (_BAM_PREDICT / "terms_fit.csv").exists(),
    reason="predict oracle missing — run tests/r_oracle/dump_bam_predict.R",
)
def test_predict_terms_iterms_exclude_matches_mgcv():
    """bam.predict's widened surface == mgcv predict.bam (P4).

    predict.bam delegates the non-discrete case to predict.gam; before P4 hea
    rejected type='terms'/'iterms' and ignored terms=/exclude=/unconditional,
    and even after un-gating, bam dropped every parametric term (missing
    _param_assign) and mis-computed the iterms cmX widening (using the p×p R
    factor for column means). All fixed; pinned here on the gauss fit where
    hea-bam coef matches mgcv-bam to ~1e-9.
    """
    df = pl.read_csv(str(_BAM_SUMMARY / "gauss" / "data.csv"))
    m = hea.models.bam("y ~ z + s(x, k=10)", df)

    # type='terms' point estimates (parametric z must be present + centered
    # like mgcv; the missing-_param_assign bug silently dropped it).
    mg_tf = pl.read_csv(str(_BAM_PREDICT / "terms_fit.csv"))
    hea_tf = m.predict(type="terms")
    assert hea_tf.columns == ["z", "s(x)"] == mg_tf.columns
    np.testing.assert_allclose(hea_tf.to_numpy(), mg_tf.to_numpy(),
                               rtol=1e-5, atol=1e-6)

    # type='terms' SEs.
    mg_ts = pl.read_csv(str(_BAM_PREDICT / "terms_se.csv")).to_numpy()
    ts = m.predict(type="terms", se_fit=True)
    hea_ts = np.column_stack([ts["se.z"].to_numpy(), ts["se.s(x)"].to_numpy()])
    np.testing.assert_allclose(hea_ts, mg_ts, rtol=1e-5, atol=1e-6)

    # type='iterms' SEs — the cmX-widened smooth SE; exercises _chunked_colmeans.
    mg_is = pl.read_csv(str(_BAM_PREDICT / "iterms_se.csv")).to_numpy()
    it = m.predict(type="iterms", se_fit=True)
    hea_is = np.column_stack([it["se.z"].to_numpy(), it["se.s(x)"].to_numpy()])
    np.testing.assert_allclose(hea_is, mg_is, rtol=1e-5, atol=1e-6)

    # exclude= a smooth → partial linear predictor on the link scale.
    with open(_BAM_PREDICT / "link_excl_sx.csv") as f:
        mg_le = np.array([float(x) for x in f.read().split()])
    hea_le = m.predict(type="link", exclude=["s(x)"])["fit"].to_numpy()
    np.testing.assert_allclose(hea_le, mg_le, rtol=1e-5, atol=1e-7)


def test_predict_unconditional_accepted():
    """unconditional= is plumbed through and returns finite SE (P4).

    Not pinned vs mgcv: mgcv reports Vc unavailable for this fit and silently
    falls back to Vp, while hea-bam carries Vc — a Vc-availability difference
    outside P4's predict-plumbing scope.
    """
    df = pl.read_csv(str(_BAM_SUMMARY / "gauss" / "data.csv"))
    m = hea.models.bam("y ~ z + s(x, k=10)", df)
    se_vp = m.predict(type="link", se_fit=True)["se.fit"].to_numpy()
    se_vc = m.predict(type="link", se_fit=True,
                      unconditional=True)["se.fit"].to_numpy()
    assert se_vc.shape == se_vp.shape
    assert np.all(np.isfinite(se_vc)) and np.all(se_vc >= 0.0)


# =============================================================================
# 1c. predict.bamd — discrete (binned) prediction path (F1)
# =============================================================================

_BAM_PREDICT_D = Path(__file__).parent / "fixtures" / "bam_predict_discrete"


@pytest.mark.skipif(
    not (_BAM_PREDICT_D / "gauss" / "data.csv").exists(),
    reason="predict.bamd oracle missing — run "
           "tests/r_oracle/dump_bam_predict_discrete.R",
)
@pytest.mark.parametrize("tag,family", [
    ("gauss", None),
    ("pois", Poisson()),
])
def test_predict_bamd_matches_mgcv(tag, family):
    """Discrete bam prediction == mgcv predict.bamd (F1).

    Before F1, hea routed discrete fits through predict.gam (exact basis
    evaluation); mgcv routes them through predict.bamd, which bins newdata's
    covariates to the compress.df grid and gathers via the discrete kernels.
    For a continuous covariate the binning is lossy, so exact-eval diverged
    from mgcv (and broke ``lpmatrix @ coef == fitted``). The fit uses the
    DEFAULT discretisation on n=3000 (where hea-bam matches mgcv-bam) but
    n > 1000 grid levels, so the binning is genuinely lossy — exact-eval
    differs from mgcv-bamd by ~3e-3, this port matches to fit precision.

    coef / lpmatrix are basis-GAUGE dependent (hea and mgcv use different but
    equivalent s(x) parameterisations), so they are NOT compared directly;
    every gauge-INVARIANT prediction (link, response, SE on both scales) is.
    """
    base = _BAM_PREDICT_D / tag

    def L(nm):
        return np.loadtxt(str(base / nm))

    df = pl.read_csv(str(base / "data.csv"))
    kw = dict(family=family) if family is not None else {}
    m = hea.models.bam("y ~ s(x, k=15)", df, discrete=True, **kw)
    coef = np.asarray(m.coefficients).reshape(-1)

    # --- training-data predictions (newdata=None) ---
    tol = dict(rtol=1e-5, atol=1e-6)
    np.testing.assert_allclose(
        m.predict(type="link")["fit"].to_numpy(), L("train_link.csv"), **tol)
    np.testing.assert_allclose(
        m.predict(type="response")["fit"].to_numpy(), L("train_fitted.csv"),
        **tol)
    np.testing.assert_allclose(
        m.predict(type="link", se_fit=True)["se.fit"].to_numpy(),
        L("train_se.csv"), **tol)

    # F1 consistency: the binned lpmatrix reproduces the link prediction
    # exactly (exact-eval breaks this for a continuous discrete fit).
    lp = m.predict(type="lpmatrix")
    assert lp.shape == (m.n, m.p)
    np.testing.assert_allclose(lp @ coef, m.linear_predictors,
                               rtol=0, atol=1e-9)

    # --- novel newdata: dense grid that re-discretises (binned, lossy) ---
    xg = L("nd_x.csv")
    nd = pl.DataFrame({"x": xg})
    np.testing.assert_allclose(
        m.predict(nd, type="link")["fit"].to_numpy(), L("nd_link.csv"), **tol)
    np.testing.assert_allclose(
        m.predict(nd, type="response")["fit"].to_numpy(), L("nd_resp.csv"),
        **tol)
    np.testing.assert_allclose(
        m.predict(nd, type="link", se_fit=True)["se.fit"].to_numpy(),
        L("nd_se.csv"), **tol)
    np.testing.assert_allclose(
        m.predict(nd, type="response", se_fit=True)["se.fit"].to_numpy(),
        L("nd_resp_se.csv"), **tol)
    # NB: exact basis eval would miss mgcv predict.bamd by ~3e-3 here (the
    # lossy binning), so the rtol=1e-5 match above already guards against a
    # regression to the old exact-eval path.


# =============================================================================
# 2. chicago oracle (Phase 3)
# =============================================================================

_CHICAGO = Path(__file__).parent / "fixtures" / "chicago"


def _load_chicago():
    return pl.read_csv(str(_CHICAGO / "data.csv"))


def _to_dat(df: pl.DataFrame) -> dict:
    return {col: df[col].to_numpy().astype(float) for col in df.columns}


@pytest.mark.skipif(
    not (_CHICAGO / "data.csv").exists(),
    reason="chicago oracle missing — run tests/r_oracle/dump_bam_chicago.R",
)
def test_chicago_simple():
    """5-smooth Poisson on chicago, no matrix args."""
    dat = _to_dat(_load_chicago())
    m = hea.models.bam(
        "death ~ s(time, k=200) + s(pm10median) + s(o3median) + "
        "s(so2median) + s(tmpd)",
        dat, family=Poisson(), discrete=True,
    )
    fit_mgcv = np.loadtxt(_CHICAGO / "simple" / "fitted.csv")
    fit_hea = np.asarray(m.fitted_values)
    rel_fit = float(
        np.linalg.norm(fit_hea - fit_mgcv) / np.linalg.norm(fit_mgcv)
    )
    assert rel_fit < 1e-5, (
        f"chicago simple fitted rel diff {rel_fit:.3e} > 1e-5"
    )

    sp_mgcv = np.atleast_1d(np.loadtxt(_CHICAGO / "simple" / "sp.csv"))
    sp_hea = np.asarray(m.sp)
    log_sp_diff = np.abs(np.log(sp_hea) - np.log(sp_mgcv))
    # 15× upper bound covers the flat-basin sp ambiguity (log15 ≈ 2.7).
    # Tighten only after Phase 2′.7 (POI optimizer) lands.
    assert float(log_sp_diff.max()) < 3.0, (
        f"chicago simple sp out of basin: hea={sp_hea}, mgcv={sp_mgcv}"
    )


@pytest.mark.skipif(
    not (_CHICAGO / "data.csv").exists(),
    reason="chicago oracle missing — run tests/r_oracle/dump_bam_chicago.R",
)
def test_chicago_lag():
    """Distributed-lag matrix-arg te() on chicago — exercises the
    matrix-arg ``compress_df`` shuffle / pad path that Phase 1 fixed."""
    dat = _to_dat(_load_chicago())

    # Build the lag matrix (exact mirror of dump_bam_chicago.R::lagard).
    def lagard(x, n_lag=6):
        n = len(x)
        X = np.full((n, n_lag), np.nan)
        for i in range(1, n_lag + 1):
            X[i - 1: n, i - 1] = x[: n - i + 1]
        return X

    pm10_lag = lagard(dat["pm10median"], n_lag=6)
    n = len(dat["pm10median"])
    lag_idx = np.tile(np.arange(6, dtype=float), (n, 1))
    good = ~np.any(np.isnan(pm10_lag), axis=1)
    dat2 = {k: v[good] for k, v in dat.items()}
    dat2["pm10_lag"] = pm10_lag[good]
    dat2["lag_idx"] = lag_idx[good]

    m = hea.models.bam(
        "death ~ s(time, k=200) + te(pm10_lag, lag_idx, k=c(10, 5)) "
        "+ s(tmpd)",
        dat2, family=Poisson(), discrete=True,
    )
    fit_mgcv = np.loadtxt(_CHICAGO / "lag" / "fitted.csv")
    fit_hea = np.asarray(m.fitted_values)
    rel_fit = float(
        np.linalg.norm(fit_hea - fit_mgcv) / np.linalg.norm(fit_mgcv)
    )
    # POI optimizer brings chicago lag to ~5e-9 on fitted; tightened
    # from the original 1e-2 bound so future regressions are caught.
    assert rel_fit < 1e-7, (
        f"chicago lag fitted rel diff {rel_fit:.3e} > 1e-7"
    )

    sp_mgcv = np.atleast_1d(np.loadtxt(_CHICAGO / "lag" / "sp.csv"))
    sp_hea = np.asarray(m.sp)
    log_sp_diff = np.abs(np.log(sp_hea) - np.log(sp_mgcv))
    # POI lands on the same minimum as mgcv to 7 significant digits on
    # chicago lag — tighten the bound so a regression flips this test.
    assert float(log_sp_diff.max()) < 1e-4, (
        f"chicago lag sp out of basin: hea={sp_hea}, mgcv={sp_mgcv}"
    )


# =============================================================================
# 2b. RF signal-regression: matrix-argument by= under discrete=True (RF1)
# =============================================================================
#
# bam(discrete=TRUE) with a matrix-argument ``by=`` (mgcv summation
# convention) was the RF1 blocker — ``_term_full_design`` applied the
# (n, n_sum) by-matrix as a length-n scalar mask AFTER the row-sum and
# raised a broadcast error. The fix multiplies the by per summation column
# BEFORE the row-sum (mgcv smooth.r:3997-4008), mirroring the non-discrete
# S1c path (formula.py:_summation_apply_blocks).
#
# mgcv ``bam(discrete=TRUE)`` (bamT) BINS the matrix-arg by-variable
# (bam.r:2469-2483: ``by.var <- dk$mf[[termk]]``; weight ``by.var[dk$k]``) —
# a lossy step for a continuous by. hea ``discrete=True`` now replicates this
# (RF1a fix): it weights the smooth by the **binned** by, so it pins to bamT
# tightly. The EXACT (un-binned) by lives at ``bam(discrete=FALSE)`` (bamF) —
# a continuous by makes bamF ≠ bamT by ~1e-3. Sourcing the raw by under
# discrete=TRUE would be a parity bug (reproducing bamF under the bamT flag);
# the bamF check below carries a lower bound to guard against that regression.
# See .claude/plans/bam-rf1a-binned-by-parity.md.

_RF_BY = Path(__file__).parent / "fixtures" / "bam_rf_by"


def _load_rf_matrix(name: str, cols: list[str]) -> dict:
    out = {}
    for c in cols:
        arr = pl.read_csv(str(_RF_BY / f"{name}_{c}.csv")).to_numpy().astype(float)
        out[c] = arr.ravel() if c == "y" else arr
    return out


@pytest.mark.skipif(
    not (_RF_BY / "te" / "bamF_fitted.csv").exists(),
    reason="bam_rf_by oracle missing — run tests/r_oracle/dump_bam_rf_by.R",
)
def test_bam_discrete_matrix_by_2d_matches_mgcv():
    """2-D ``te(Lag, Xc, by=Stim)`` signal regression under discrete=True.

    Parity (RF1a): mgcv ``bam(discrete=TRUE)`` makes the by the term's first
    rank-1 marginal (bam.r:2470-2482) and the fit applies the **binned** by
    ``by.var[k[:, ks_by+q]]`` per summation column (discrete.c:tensorXb). hea
    weights the smooth by that same binned by, so discrete=True must match
    **bamT**, not bamF (exact-by, which lives at discrete=False).
    """
    sub = "te"
    d = _load_rf_matrix(sub, ["y"])
    M = _load_rf_matrix(sub, ["Lag", "Xc", "Stim"])
    dat = {"y": d["y"], "Lag": M["Lag"], "Xc": M["Xc"], "Stim": M["Stim"]}
    f = "y ~ te(Lag, Xc, by=Stim, k=c(4,3))"

    m = hea.models.bam(f, dat, family=Poisson(), discrete=True)

    fitF = np.loadtxt(_RF_BY / sub / "bamF_fitted.csv")
    fitT = np.loadtxt(_RF_BY / sub / "bamT_fitted.csv")
    edfT = float(np.loadtxt(_RF_BY / sub / "bamT_edfsum.csv"))
    fit_hea = np.asarray(m.fitted_values)

    rel_F = float(np.linalg.norm(fit_hea - fitF) / np.linalg.norm(fitF))
    rel_T = float(np.linalg.norm(fit_hea - fitT) / np.linalg.norm(fitT))
    # Binned-by equivalence to mgcv bam(discrete=TRUE): the meaningful pin.
    assert rel_T < 1e-6, f"hea-discrete vs mgcv bamT fitted rel {rel_T:.2e} > 1e-6"
    assert abs(float(np.sum(m.edf)) - edfT) < 1e-4, (
        f"edf {np.sum(m.edf):.5f} vs mgcv bamT {edfT:.5f}"
    )
    # The exact (un-binned) by lives at discrete=False (== bamF); discrete=True
    # is ~1e-3 off it. The lower bound guards against silently reverting to
    # exact-by (the RF1a parity bug), which would collapse rel_F to ~1e-8.
    assert 1e-4 < rel_F < 5e-3, (
        f"hea-discrete vs mgcv bamF fitted rel {rel_F:.2e} not in (1e-4, 5e-3)"
    )


@pytest.mark.skipif(
    not (_RF_BY / "s" / "bamF_fitted.csv").exists(),
    reason="bam_rf_by oracle missing — run tests/r_oracle/dump_bam_rf_by.R",
)
def test_bam_discrete_matrix_by_1d_matches_mgcv():
    """1-D ``s(Lag, by=Stim)`` signal regression under discrete=True."""
    sub = "s"
    d = _load_rf_matrix(sub, ["y"])
    M = _load_rf_matrix(sub, ["Lag", "Stim"])
    dat = {"y": d["y"], "Lag": M["Lag"], "Stim": M["Stim"]}
    f = "y ~ s(Lag, by=Stim, k=8)"

    m = hea.models.bam(f, dat, family=Poisson(), discrete=True)

    fitF = np.loadtxt(_RF_BY / sub / "bamF_fitted.csv")
    fitT = np.loadtxt(_RF_BY / sub / "bamT_fitted.csv")
    edfT = float(np.loadtxt(_RF_BY / sub / "bamT_edfsum.csv"))
    fit_hea = np.asarray(m.fitted_values)

    rel_F = float(np.linalg.norm(fit_hea - fitF) / np.linalg.norm(fitF))
    rel_T = float(np.linalg.norm(fit_hea - fitT) / np.linalg.norm(fitT))
    # Binned-by equivalence to mgcv bam(discrete=TRUE): the meaningful pin.
    assert rel_T < 1e-6, f"hea-discrete vs mgcv bamT fitted rel {rel_T:.2e} > 1e-6"
    assert abs(float(np.sum(m.edf)) - edfT) < 1e-4, (
        f"edf {np.sum(m.edf):.5f} vs mgcv bamT {edfT:.5f}"
    )
    # Exact-by lives at discrete=False (== bamF); discrete=True is ~1e-3 off.
    # Lower bound guards against silently reverting to exact-by (RF1a bug).
    assert 1e-4 < rel_F < 5e-3, (
        f"hea-discrete vs mgcv bamF fitted rel {rel_F:.2e} not in (1e-4, 5e-3)"
    )


@pytest.mark.skipif(
    not (_RF_BY / "te_ridge" / "bamT_fitted.csv").exists(),
    reason="bam_rf_by oracle missing — run tests/r_oracle/dump_bam_rf_by.R",
)
def test_bam_discrete_matrix_by_ridge_basin_matches_mgcv():
    """RF1b regression guard: a near-ridge ``te(Lag, Xc, by=Stim)`` whose true
    RF varies in Lag but is ~flat in Xc, so the fREML sp-search pushes the Xc
    margin onto a near-linear ridge (sp ~5e3).

    This is the regime where hea's OLD exact-by ``discrete=True`` design built a
    different REML surface than mgcv and the outer sp-search landed in a worse
    basin (edf 6.81 vs mgcv 10.65 — RF1b). RF1a (bin the by like mgcv,
    bam.r:2470-2482) aligned the design, hence the surface, hence the basin: hea
    ``discrete=True`` now tracks mgcv **bamT** into the SAME basin. A basin
    regression would move edf by ~O(1), so the tight bamT pin trips hard on any
    recurrence. The case is well-determined (sp ~5472 vs ~30, both modes agree
    to 1e-4) — not flat-optimum indeterminacy.
    """
    sub = "te_ridge"
    d = _load_rf_matrix(sub, ["y"])
    M = _load_rf_matrix(sub, ["Lag", "Xc", "Stim"])
    dat = {"y": d["y"], "Lag": M["Lag"], "Xc": M["Xc"], "Stim": M["Stim"]}
    f = "y ~ te(Lag, Xc, by=Stim, k=c(4,3))"

    m = hea.models.bam(f, dat, family=Poisson(), discrete=True)

    fitF = np.loadtxt(_RF_BY / sub / "bamF_fitted.csv")
    fitT = np.loadtxt(_RF_BY / sub / "bamT_fitted.csv")
    edfT = float(np.loadtxt(_RF_BY / sub / "bamT_edfsum.csv"))
    fit_hea = np.asarray(m.fitted_values)

    rel_F = float(np.linalg.norm(fit_hea - fitF) / np.linalg.norm(fitF))
    rel_T = float(np.linalg.norm(fit_hea - fitT) / np.linalg.norm(fitT))
    # Same fREML basin as mgcv bamT — the RF1b guard. Measured rel_T 1.8e-7,
    # edf Δ 5e-6; a basin regression moves edf by ~O(1), tripping both pins.
    assert rel_T < 1e-5, f"hea-discrete vs mgcv bamT fitted rel {rel_T:.2e} > 1e-5"
    assert abs(float(np.sum(m.edf)) - edfT) < 1e-3, (
        f"edf {np.sum(m.edf):.5f} vs mgcv bamT {edfT:.5f} (basin drift?)"
    )
    # Binned (not exact) by: ~1.7e-3 off bamF; lower bound guards exact-by revert.
    assert 1e-4 < rel_F < 5e-3, (
        f"hea-discrete vs mgcv bamF fitted rel {rel_F:.2e} not in (1e-4, 5e-3)"
    )


@pytest.mark.skipif(
    not (_RF_BY / "te" / "bamF_fitted.csv").exists(),
    reason="bam_rf_by oracle missing — run tests/r_oracle/dump_bam_rf_by.R",
)
@pytest.mark.parametrize("sub,f,cols", [
    ("te", "y ~ te(Lag, Xc, by=Stim, k=c(4,3))", ["Lag", "Xc", "Stim"]),
    ("s", "y ~ s(Lag, by=Stim, k=8)", ["Lag", "Stim"]),
])
def test_bam_nondiscrete_matrix_by_matches_mgcv(sub, f, cols):
    """RF2: hea ``bam(discrete=FALSE)`` matrix-by — the EXACT-by chunked-PIRLS
    path (mgcv ``bgam.fit``, no n·m·p long form) — must equal mgcv
    ``bam(discrete=FALSE)`` (bamF), the exact-by home. Complements the
    ``discrete=True`` == bamT pins above (which bin the by)."""
    d = _load_rf_matrix(sub, ["y"])
    M = _load_rf_matrix(sub, cols)
    dat = {"y": d["y"]}
    dat.update(M)
    m = hea.models.bam(f, dat, family=Poisson(), discrete=False)
    fitF = np.loadtxt(_RF_BY / sub / "bamF_fitted.csv")
    edfF = float(np.loadtxt(_RF_BY / sub / "bamF_edfsum.csv"))
    fit_hea = np.asarray(m.fitted_values)
    rel_F = float(np.linalg.norm(fit_hea - fitF) / np.linalg.norm(fitF))
    assert rel_F < 1e-5, f"hea-nondiscrete vs mgcv bamF fitted rel {rel_F:.2e} > 1e-5"
    assert abs(float(np.sum(m.edf)) - edfF) < 1e-3, (
        f"edf {np.sum(m.edf):.5f} vs mgcv bamF {edfF:.5f}"
    )


@pytest.mark.skipif(
    not (_RF_BY / "te" / "bamF_tw_fitted.csv").exists(),
    reason="bam_rf_by Tweedie oracle missing — run tests/r_oracle/dump_bam_rf_by.R",
)
def test_bam_tweedie_matrix_by_matches_mgcv():
    """RF4: extended-family (Tweedie, fixed p=1.5) + matrix-by RF must equal
    mgcv ``bam(family=Tweedie(p=1.5), discrete=FALSE)`` — confirming the
    extended-family fREML cadence (B2) composes with the matrix-arg summation
    design. The ``te`` data is near-ridge (one margin sp ~1e8), so the Tweedie
    scale estimate is sensitive (~1.7e-4 edf, consistent with B2's Tweedie
    rtol) — hence the honest tolerance. Negative-binomial RF is blocked on a
    MISSING NB family in hea (a separate gap, not an RF one)."""
    from hea.family import Tweedie
    sub = "te"
    d = _load_rf_matrix(sub, ["y"])
    M = _load_rf_matrix(sub, ["Lag", "Xc", "Stim"])
    dat = {"y": d["y"]}
    dat.update(M)
    m = hea.models.bam("y ~ te(Lag, Xc, by=Stim, k=c(4,3))", dat,
                       family=Tweedie(p=1.5), discrete=False)
    fitR = np.loadtxt(_RF_BY / sub / "bamF_tw_fitted.csv")
    edfR = float(np.loadtxt(_RF_BY / sub / "bamF_tw_edfsum.csv"))
    fit_hea = np.asarray(m.fitted_values)
    rel = float(np.linalg.norm(fit_hea - fitR) / np.linalg.norm(fitR))
    assert rel < 5e-5, f"hea Tweedie-RF vs mgcv fitted rel {rel:.2e} > 5e-5"
    assert abs(float(np.sum(m.edf)) - edfR) < 1e-3, (
        f"edf {np.sum(m.edf):.5f} vs mgcv Tweedie {edfR:.5f}"
    )


def test_bam_discrete_matrix_by_kernel_path_guarded():
    """The opt-in scatter kernels don't apply by= weighting (bam-plan P2);
    they must fail loudly on a by-term, not silently miscompute."""
    from hea.models.bam import XWXd, _assert_kernels_support
    # Build a tiny matrix-by design to get a DiscreteDesign with a by-term,
    # then assert the kernel guard trips.
    rng = np.random.default_rng(0)
    n, mm = 80, 6
    Lag = np.tile(np.arange(mm, dtype=float), (n, 1))
    Stim = rng.standard_normal((n, mm))
    yv = rng.poisson(1.0, n).astype(float)
    m = hea.models.bam("y ~ s(Lag, by=Stim, k=5)",
                       {"y": yv, "Lag": Lag, "Stim": Stim},
                       family=Poisson(), discrete=True)
    design = m._discrete_design
    with pytest.raises(NotImplementedError, match="by="):
        _assert_kernels_support(design)
    with pytest.raises(NotImplementedError, match="by="):
        XWXd(design, np.ones(n), use_kernel=True)


def test_distinct_exceeds_1d_exact_vs_npunique():
    """RF1a-R5: the early-exit ``>threshold distinct?`` predicate must be
    EXACTLY ``np.unique(a).size > threshold`` (it drives compress.df's round
    decision, bam.r:152). Any disagreement would change the bamT fit. Covers
    continuous (early-exit), boundary (==, +1), binary/lattice (full scan),
    and small-n (n<=threshold) paths."""
    from hea.models.bam import _distinct_exceeds_1d
    rng = np.random.default_rng(7)
    cases = [
        rng.standard_normal(200_000),            # continuous, many distinct
        rng.integers(0, 2, 100_000).astype(float),  # binary
        np.arange(1000.0),                        # distinct == threshold -> False
        np.arange(1001.0),                        # distinct == threshold+1 -> True
        np.tile(np.arange(37.0), 5000),           # low-card lattice
        np.arange(50.0),                          # n <= threshold
        np.full(10_000, 3.0),                     # single distinct value
    ]
    for a in cases:
        assert _distinct_exceeds_1d(a, 1000) == (np.unique(a).size > 1000)
    # chunk-boundary stress: threshold below the 1<<16 step, distinct straddles it
    a = np.arange(70_000.0)
    for t in (10, 65_535, 65_536, 69_999, 70_000):
        assert _distinct_exceeds_1d(a, t) == (np.unique(a).size > t)


# =============================================================================
# 3. small_data oracle (Phase 1 + Phase 2′)
# =============================================================================

_SMALL = Path(__file__).parent / "fixtures" / "small_data"


def _load_small_dat():
    df = pl.read_csv(str(_SMALL / "data.csv"))
    pm10 = df.select(["X1", "X2", "X3", "X4"]).to_numpy().astype(float)
    lag = df.select(["X1.1", "X2.1", "X3.1", "X4.1"]).to_numpy().astype(float)
    return {"y": df["y"].to_numpy().astype(float),
            "pm10": pm10, "lag": lag}


@pytest.mark.skipif(
    not (_SMALL / "data.csv").exists(),
    reason="small_data oracle missing — see tests/r_oracle/",
)
def test_small_data_force_sp():
    """With mgcv's sp forced, hea's β must give fitted matching mgcv
    to ≤ 1e-9 (gauge-invariant predictive equivalence)."""
    dat = _load_small_dat()
    sp_mgcv = np.atleast_1d(np.loadtxt(_SMALL / "sp.csv"))
    m = hea.models.bam("y ~ te(pm10, lag, k=c(5, 3))", dat,
                family=Poisson(), discrete=True, sp=sp_mgcv)

    fit_mgcv = np.loadtxt(_SMALL / "fitted.csv")
    fit_hea = np.asarray(m.fitted_values)
    rel_fit = float(
        np.linalg.norm(fit_hea - fit_mgcv) / np.linalg.norm(fit_mgcv)
    )
    assert rel_fit < 1e-9, (
        f"small_data force-sp fitted rel diff {rel_fit:.3e} > 1e-9"
    )


@pytest.mark.skipif(
    not (_SMALL / "data.csv").exists(),
    reason="small_data oracle missing",
)
def test_small_data_auto_sp():
    """Auto-sp on the rank-deficient small_data model lands in a
    different specific basin point than mgcv, but fitted should still
    be within 1e-5 because the basin is flat and both impls minimise
    REML to machine precision."""
    dat = _load_small_dat()
    m = hea.models.bam("y ~ te(pm10, lag, k=c(5, 3))", dat,
                family=Poisson(), discrete=True)

    fit_mgcv = np.loadtxt(_SMALL / "fitted.csv")
    fit_hea = np.asarray(m.fitted_values)
    rel_fit = float(
        np.linalg.norm(fit_hea - fit_mgcv) / np.linalg.norm(fit_mgcv)
    )
    assert rel_fit < 1e-5, (
        f"small_data auto-sp fitted rel diff {rel_fit:.3e} > 1e-5"
    )




def test_mini_mf_matches_mgcv():
    """mini.mf (bam.r:384-427) row selection is bit-exact: temp.seed(66)
    + sample(1:n, chunk.size) + sample(1:n, n) through the hea.R.rng
    port, factor levels picked as the first match in the RANDOMIZED row
    order, levels in R's order, numeric min/max rows overwriting the
    head. Reference: mgcv:::mini.mf on a 500-row frame (x = runif
    rounded to 6dp, fac = 4 letters), chunk_size=100."""
    from hea.models.bam import _mini_mf
    # Regenerate the R probe frame exactly (R: set.seed(99); x =
    # round(runif(n), 6); fac = sample(letters[1:4], n, TRUE)) via the
    # R RNG port — runif stream then R sample() with replacement.
    from hea.R import RMersenneTwister
    r = RMersenneTwister(99)
    n = 500
    x = np.round(r.unif_rand(n), 6)
    lv = np.array(["a", "b", "c", "d"])
    fac = lv[r.sample_int(4, n, replace=True)]
    df = pl.DataFrame({"x": x, "fac": fac})
    mf0 = _mini_mf(df, 100)
    assert mf0.height == 100
    np.testing.assert_allclose(
        mf0["x"].to_numpy()[:8],
        [0.001179, 0.996862, 0.552895, 0.040490, 0.090266, 0.396683,
         0.097112, 0.193021], atol=1e-9)
    assert mf0["fac"].to_list()[:8] == list("ccabcdaa")
    np.testing.assert_allclose(float(mf0["x"].sum()), 45.676350,
                               atol=1e-6)


# =============================================================================
# 4. summary() / rank parity — P1, P5
# =============================================================================
# Oracles: tests/r_oracle/dump_bam_summary.R → tests/fixtures/bam_summary/
# {gauss,pois,rankdef}/ (summary.gam p.table / s.table / scale / r.sq /
# dev.expl / sp.criterion + m$rank). Tolerance bands follow the BLAS
# flat-optimum rule: well-determined fit quantities (coef, scale, r.sq,
# dev.expl, the Gaussian fREML value) pin tight; inverse-Hessian / trace
# quantities (SE, per-smooth edf) get the ~1e-5 band. The Poisson fREML *value*
# is deliberately NOT pinned — hea's non-Gaussian criterion carries a constant
# saturated-likelihood offset vs mgcv's sp.criterion (the argmin/fit are
# unaffected); closing that is plan item P16.


def _summ_meta(name: str) -> dict:
    with open(_BAM_SUMMARY / name / "meta.csv", newline="") as f:
        row = next(csv.DictReader(f))
    return {k: float(v) for k, v in row.items()}


def _summ_ptable(name: str):
    """summary.gam p.table keyed by coefficient name, plus the header."""
    out = {}
    with open(_BAM_SUMMARY / name / "ptable.csv", newline="") as f:
        reader = csv.reader(f)
        header = next(reader)            # "", Estimate, Std. Error, stat, p
        for r in reader:
            out[r[0]] = [float(v) for v in r[1:]]
    return out, header


def _summ_stable(name: str) -> dict:
    """summary.gam s.table keyed by smooth label (edf, Ref.df, stat, p)."""
    out = {}
    with open(_BAM_SUMMARY / name / "stable.csv", newline="") as f:
        reader = csv.reader(f)
        next(reader)
        for r in reader:
            out[r[0]] = [float(v) for v in r[1:]]
    return out


def _summary_text(m) -> str:
    buf = io.StringIO()
    with redirect_stdout(buf):
        m.summary()
    return buf.getvalue()


def _check_parametric(m, ptable, *, est_rtol, se_rtol):
    """Estimate + Std. Error pinned by coefficient name."""
    for name, (est, se, _stat, _p) in ptable.items():
        np.testing.assert_allclose(
            float(m.coef[name]), est, rtol=est_rtol, err_msg=f"{name} estimate")
        np.testing.assert_allclose(
            float(m.se_bhat[name][0]), se, rtol=se_rtol, err_msg=f"{name} se")


@pytest.mark.skipif(
    not (_BAM_SUMMARY / "gauss" / "meta.csv").exists(),
    reason="summary oracle missing — run tests/r_oracle/dump_bam_summary.R",
)
def test_bam_summary_gaussian():
    """Gaussian-identity bam (_post_fit_gaussian): full summary parity."""
    df = pl.read_csv(str(_BAM_SUMMARY / "gauss" / "data.csv"))
    m = hea.models.bam("y ~ z + s(x, k=10)", df)
    # P1 regression guard: summary() must not raise.
    txt = _summary_text(m)
    assert "Parametric coefficients" in txt
    assert "Approximate significance of smooth terms" in txt

    meta = _summ_meta("gauss")
    assert m.rank == int(meta["rank"]) == m.p          # P5: full rank 11/11
    np.testing.assert_allclose(m.sigma_squared, meta["scale"], rtol=1e-6)
    np.testing.assert_allclose(m.r_squared_adjusted, meta["r.sq"], rtol=1e-6)
    np.testing.assert_allclose(m.deviance_explained, meta["dev.expl"], rtol=1e-6)
    # Gaussian fREML value matches mgcv's sp.criterion (hea reports 2·V_R).
    np.testing.assert_allclose(m.REML_criterion / 2, meta["sp.criterion"],
                               atol=1e-3)

    ptable, header = _summ_ptable("gauss")
    assert header[3] == "t value"                      # scale estimated → t/F
    _check_parametric(m, ptable, est_rtol=1e-6, se_rtol=1e-5)

    stable = _summ_stable("gauss")
    np.testing.assert_allclose(m.edf_by_smooth["s(x)"], stable["s(x)"][0],
                               rtol=1e-5)


@pytest.mark.skipif(
    not (_BAM_SUMMARY / "pois" / "meta.csv").exists(),
    reason="summary oracle missing — run tests/r_oracle/dump_bam_summary.R",
)
def test_bam_summary_poisson():
    """Poisson-log bam (_post_fit_pirls), scale known: full summary parity.

    The fREML criterion *value* is now pinned too (P16): bam's _reml used the
    working-data RSS where mgcv's fREML uses the response deviance; the post-fit
    correction (swap dev in Dp/φ) matches mgcv-bam's sp.criterion.
    """
    df = pl.read_csv(str(_BAM_SUMMARY / "pois" / "data.csv"))
    m = hea.models.bam("y ~ z + s(x, k=10)", df, family=Poisson())
    txt = _summary_text(m)
    assert "Parametric coefficients" in txt
    # known-scale family → z/Chi.sq columns, "Scale est. = 1".
    assert "z value" in txt and "Chi.sq" in txt

    meta = _summ_meta("pois")
    assert m.rank == int(meta["rank"]) == m.p
    assert m.scale == 1.0 == meta["scale"]
    np.testing.assert_allclose(m.deviance_explained, meta["dev.expl"], rtol=1e-6)
    # P16: non-Gaussian fREML value matches mgcv's sp.criterion.
    np.testing.assert_allclose(m.REML_criterion / 2, meta["sp.criterion"],
                               rtol=1e-6)

    ptable, header = _summ_ptable("pois")
    assert header[3] == "z value"
    _check_parametric(m, ptable, est_rtol=1e-6, se_rtol=1e-5)

    stable = _summ_stable("pois")
    np.testing.assert_allclose(m.edf_by_smooth["s(x)"], stable["s(x)"][0],
                               rtol=1e-5)


@pytest.mark.skipif(
    not (_BAM_SUMMARY / "rankdef" / "meta.csv").exists(),
    reason="summary oracle missing — run tests/r_oracle/dump_bam_summary.R",
)
def test_bam_summary_rank_deficient():
    """Collinear parametric column → m.rank = p-1 and a `Rank: r/p` line.

    The dropped direction is gauge-dependent (x vs its exact copy xdup), so
    individual collinear coefs are not pinned; rank, the printed rank line,
    and gauge-invariant fit summaries (dev.expl) are.
    """
    df = pl.read_csv(str(_BAM_SUMMARY / "rankdef" / "data.csv"))
    m = hea.models.bam("y ~ x + xdup + s(z, k=6)", df)
    meta = _summ_meta("rankdef")
    assert m.rank == int(meta["rank"]) == 7
    assert m.rank < m.p == int(meta["p"]) == 8

    txt = _summary_text(m)
    assert f"Rank: {m.rank}/{m.p}" in txt                # P5 + summary's rank line
    # deviance explained agrees to a sanity band — the exact value drifts ~5e-4
    # because hea and mgcv drop the collinear direction at slightly different
    # points of the rank-reveal (BLAS-bistable on the flat direction), not
    # fully gauge-invariant when crossed with the s(z) penalty.
    np.testing.assert_allclose(m.deviance_explained, meta["dev.expl"], atol=5e-3)


# =============================================================================
# 5. prior weights= parity — P2
# =============================================================================
# Oracles: tests/r_oracle/dump_bam_weights.R → tests/fixtures/bam_weights/
# {gauss,pois}/. bam(weights=) used to raise TypeError and hardcode
# self._wt = ones; now weights thread through the chunked QR build (√w rows),
# the PIRLS Fisher weights, and every post-fit consumer. Pinned on
# gauge-invariant quantities: fitted μ̂, scale, edf, dev.expl, rank, and the
# parametric coef/SE. Raw smooth-basis coefs are NOT pinned — hea's smooth
# basis parametrisation differs from mgcv's (the fitted function is identical).

_BAM_WEIGHTS = Path(__file__).parent / "fixtures" / "bam_weights"


def _weights_oracle(name: str):
    meta = {}
    with open(_BAM_WEIGHTS / name / "meta.csv", newline="") as f:
        meta = {k: float(v) for k, v in next(csv.DictReader(f)).items()}
    coef = {}
    with open(_BAM_WEIGHTS / name / "coef.csv", newline="") as f:
        r = csv.reader(f)
        next(r)
        for row in r:
            coef[row[0]] = float(row[1])
    with open(_BAM_WEIGHTS / name / "fitted.csv") as f:
        fitted = np.array([float(x) for x in f.read().split()])
    return meta, coef, fitted


@pytest.mark.skipif(
    not (_BAM_WEIGHTS / "gauss" / "meta.csv").exists(),
    reason="weights oracle missing — run tests/r_oracle/dump_bam_weights.R",
)
@pytest.mark.parametrize("name,fam", [("gauss", None), ("pois", "poisson")])
def test_bam_prior_weights_match_mgcv(name, fam):
    """hea bam(weights=w) == mgcv bam(weights=w) on the gauge-invariant fit."""
    df = pl.read_csv(str(_BAM_WEIGHTS / name / "data.csv"))
    w = df["w"].to_numpy().astype(float)
    kw = {"weights": w}
    if fam == "poisson":
        kw["family"] = Poisson()
    m = hea.models.bam("y ~ z + s(x, k=10)", df, **kw)
    meta, coef, fitted = _weights_oracle(name)

    np.testing.assert_allclose(m.fitted_values, fitted, atol=1e-6)
    np.testing.assert_allclose(m.scale, meta["scale"], rtol=1e-5)
    np.testing.assert_allclose(m.edf_total, meta["edf_total"], rtol=1e-5)
    assert m.rank == int(meta["rank"])
    np.testing.assert_allclose(m.deviance_explained, meta["dev.expl"], rtol=1e-6)
    # parametric coefs + intercept SE (gauge-invariant under the smooth basis).
    np.testing.assert_allclose(float(m.coef["(Intercept)"]), coef["(Intercept)"],
                               rtol=1e-5)
    np.testing.assert_allclose(float(m.coef["z"]), coef["z"], rtol=1e-5)
    np.testing.assert_allclose(float(m.se_bhat["(Intercept)"][0]),
                               meta["int_se"], rtol=1e-5)


def test_bam_weights_validation():
    """weights= is accepted (no longer TypeError) and validated."""
    df = pl.read_csv(str(_BAM_SUMMARY / "gauss" / "data.csv"))
    n = df.height
    # accepted: ones ≡ the unweighted fit.
    m_w1 = hea.models.bam("y ~ z + s(x, k=10)", df, weights=np.ones(n))
    m_u = hea.models.bam("y ~ z + s(x, k=10)", df)
    np.testing.assert_allclose(m_w1.fitted_values, m_u.fitted_values,
                               rtol=1e-10, atol=1e-12)
    # wrong length / negative weights rejected.
    with pytest.raises(ValueError, match="length"):
        hea.models.bam("y ~ z + s(x, k=10)", df, weights=np.ones(n - 1))
    with pytest.raises(ValueError, match="non-negative"):
        bad = np.ones(n); bad[0] = -1.0
        hea.models.bam("y ~ z + s(x, k=10)", df, weights=bad)


# =============================================================================
# 6. scale= argument — P6
# =============================================================================
# Oracle: tests/r_oracle/dump_bam_scale.R → tests/fixtures/bam_scale/. bam took
# no scale= arg (TypeError). Now scale>0 fixes φ for scale-unknown families
# (REML selects sp with φ held fixed → a different fit than the φ-estimated
# default); scale<0 forces estimation (≡ default for those families). Scale-
# known families (poisson/binomial) only accept scale=0 — bam's quasi-likelihood
# dispersion estimation needs a PIRLS φ-slot hea doesn't carry for them.

_BAM_SCALE = Path(__file__).parent / "fixtures" / "bam_scale"


@pytest.mark.skipif(
    not (_BAM_SCALE / "meta.csv").exists(),
    reason="scale oracle missing — run tests/r_oracle/dump_bam_scale.R",
)
def test_bam_scale_fixed_gaussian_matches_mgcv():
    """bam(scale=2.5) on a Gaussian == mgcv bam(scale=2.5)."""
    df = pl.read_csv(str(_BAM_SUMMARY / "gauss" / "data.csv"))
    m = hea.models.bam("y ~ z + s(x, k=10)", df, scale=2.5)
    with open(_BAM_SCALE / "meta.csv", newline="") as f:
        meta = {k: float(v) for k, v in next(csv.DictReader(f)).items()}
    with open(_BAM_SCALE / "fitted.csv") as f:
        fitted = np.array([float(x) for x in f.read().split()])

    assert m.scale == 2.5 == meta["scale"]            # φ fixed at the user value
    assert not m.scale_estimated
    np.testing.assert_allclose(m.edf_total, meta["edf_total"], rtol=1e-5)
    np.testing.assert_allclose(float(m.sp[0]), meta["sp"], rtol=1e-4)
    np.testing.assert_allclose(m.fitted_values, fitted, atol=1e-6)
    np.testing.assert_allclose(float(m.coef["(Intercept)"]), meta["int_est"],
                               rtol=1e-5)
    np.testing.assert_allclose(float(m.se_bhat["(Intercept)"][0]),
                               meta["int_se"], rtol=1e-5)


def test_bam_scale_semantics():
    """scale=0 default, scale<0 ≡ estimate (scale-unknown), known-family guard."""
    from hea.family import Poisson
    dg = pl.read_csv(str(_BAM_SUMMARY / "gauss" / "data.csv"))
    # scale<0 on a Gaussian forces estimation — identical to the default.
    m_neg = hea.models.bam("y ~ z + s(x, k=10)", dg, scale=-1.0)
    m_def = hea.models.bam("y ~ z + s(x, k=10)", dg)
    np.testing.assert_allclose(m_neg.fitted_values, m_def.fitted_values,
                               rtol=1e-10, atol=1e-12)
    assert m_neg.scale_estimated
    # scale-known family: only scale=0 supported; nonzero raises.
    dp = pl.read_csv(str(_BAM_SUMMARY / "pois" / "data.csv"))
    assert hea.models.bam("y ~ z + s(x, k=10)", dp, family=Poisson(),
                          scale=0).scale == 1.0
    for bad in (-1.0, 2.5):
        with pytest.raises(NotImplementedError, match="scale-known"):
            hea.models.bam("y ~ z + s(x, k=10)", dp, family=Poisson(),
                           scale=bad)
    # non-finite scale rejected.
    with pytest.raises(ValueError, match="finite"):
        hea.models.bam("y ~ z + s(x, k=10)", dg, scale=float("inf"))


# =============================================================================
# 7. id= smoothing-parameter sharing — the L-matrix layer (plan item P9)
# =============================================================================
# bam used to REJECT id= (reject_unsupported_smooth_id): each linked penalty
# would silently get its own λ. bam now ports gam's working-θ L layer —
# ρ_full = L·θ maps ONE working smoothing parameter onto several penalties, the
# bases are pooled across the linked smooths (idLinksBases, shared through
# materialize_smooths), and the optimisers + post-fit run in working space
# (g_θ = T'g, H_θ = T'HT, T = blockdiag(L, I)). Pinned vs mgcv **bam** (not
# gam): bam builds bases on the mini.mf subsample, so the criterion's absolute
# log-determinants carry a basis-dependent constant for data-quantile-knot
# bases (cr) — the FIT (sp/edf/fitted/scale) is gauge-invariant and DOES pin.
# Oracle: tests/r_oracle/dump_bam_id.R → tests/fixtures/bam_id/.
_BAM_ID = Path(__file__).parent / "fixtures" / "bam_id"


def _id_col(case, name):
    return np.array(
        [float(x) for x in (_BAM_ID / case / name).read_text().split()])


def _id_meta(case):
    with open(_BAM_ID / case / "meta.csv", newline="") as f:
        return {k: float(v) for k, v in next(csv.DictReader(f)).items()}


def _id_stable(case):
    """summary s.table per-smooth edf, keyed by smooth label (col 0 → edf)."""
    out = {}
    with open(_BAM_ID / case / "stable.csv", newline="") as f:
        for row in csv.reader(f):
            if not row or not row[0]:
                continue
            try:
                out[row[0]] = float(row[1])
            except (ValueError, IndexError):
                pass
    return out


def _bam_id_data():
    """set.seed(13) data — bit-matches dump_bam_id.R's gauss cases (R-native
    runif/rnorm via hea.R.rng), for the oracle-free logic tests below."""
    from hea.R.rng import RGenerator
    g = RGenerator(13)
    n = 250
    x0 = g.uniform(0.0, 1.0, n)
    x1 = g.uniform(0.0, 3.0, n)
    y = np.sin(2 * np.pi * x0) + np.sin(2 * np.pi * x1 / 3) \
        + g.normal(0.0, 0.35, n)
    return pl.DataFrame({"x0": x0, "x1": x1, "y": y})


@pytest.mark.skipif(not (_BAM_ID / "gauss_tp" / "meta.csv").exists(),
                    reason="bam_id oracle missing — run dump_bam_id.R")
@pytest.mark.parametrize("case, formula, pin_crit", [
    ("gauss_tp", "y ~ s(x0, id=1) + s(x1, id=1)", True),
    ("gauss_cr", "y ~ s(x0, bs='cr', id=1) + s(x1, bs='cr', id=1)", False),
    ("pois", "y ~ s(x0, id=1) + s(x1, id=1)", True),
])
def test_bam_id_links_lambda_matches_mgcv(case, formula, pin_crit):
    """ONE working λ shared across the linked smooths; bases pooled over the
    union of the (different-range) covariates; the fit pins to mgcv-bam.
    gauss_tp/pois pin the fREML criterion VALUE too; gauss_cr does not — its
    data-quantile cr knots on the mini.mf subsample shift the criterion's
    absolute log-determinants (a non-id bam property as well), while
    sp/edf/fitted stay invariant and DO pin."""
    df = pl.read_csv(str(_BAM_ID / case / "data.csv"))
    fam = dict(family=Poisson()) if case == "pois" else {}
    m = hea.models.bam(formula, df, method="REML", **fam)
    meta = _id_meta(case)
    sp_ref, fsp_ref = _id_col(case, "sp.csv"), _id_col(case, "full_sp.csv")
    fit_ref, stable = _id_col(case, "fitted.csv"), _id_stable(case)
    # one working sp; two penalties share it; full.sp repeats the working value
    assert len(m.sp) == 1 == int(meta["n_work"])
    assert len(m._slots) == 2 == int(meta["n_slots"])
    np.testing.assert_allclose(np.exp(m._rho_hat), [m.sp[0]] * 2, rtol=1e-12)
    np.testing.assert_allclose(np.exp(m._rho_hat), fsp_ref, rtol=1e-4)
    np.testing.assert_allclose(m.sp, sp_ref, rtol=1e-4)
    np.testing.assert_allclose(m.sigma_squared, meta["scale"], rtol=1e-5)
    for lbl, edf in m.edf_by_smooth.items():
        np.testing.assert_allclose(edf, stable[lbl], rtol=1e-4)
    np.testing.assert_allclose(m.fitted_values, fit_ref, rtol=1e-4, atol=1e-6)
    if pin_crit:
        np.testing.assert_allclose(m.REML_criterion / 2, meta["sp_criterion"],
                                   rtol=1e-6)
    # the shared raw basis must replay at predict time (renamed view for x1)
    pred = m.predict(df.head(40))["fit"].to_numpy()
    np.testing.assert_allclose(pred, m.fitted[:40], rtol=1e-6, atol=1e-7)


@pytest.mark.skipif(not (_BAM_ID / "pois" / "meta.csv").exists(),
                    reason="bam_id oracle missing — run dump_bam_id.R")
def test_bam_id_discrete_poi_matches_mgcv():
    """The discrete POI optimiser supports id via the working-space Newton step
    (T'g, T'HT contraction of _pi_fit_chol's full per-penalty grad/Hessian).
    On these continuous covariates hea bins by unique value (discrete ≡
    non-discrete), so the discrete-id fit lands on the mgcv NON-discrete id
    reference (= mgcv gam id). mgcv's own discrete=TRUE+id re-discretises the
    pooled basis and drifts elsewhere — an mgcv-internal quirk not reproduced
    (see dump_bam_id.R)."""
    df = pl.read_csv(str(_BAM_ID / "pois" / "data.csv"))
    sp_ref = _id_col("pois", "sp.csv")
    m = hea.models.bam("y ~ s(x0, id=1) + s(x1, id=1)", df,
                       family=Poisson(), method="REML", discrete=True)
    assert len(m.sp) == 1 and len(m._slots) == 2
    np.testing.assert_allclose(np.exp(m._rho_hat), [m.sp[0]] * 2, rtol=1e-12)
    np.testing.assert_allclose(m.sp, sp_ref, rtol=1e-4)


@pytest.mark.skipif(not (_BAM_ID / "byfac" / "meta.csv").exists(),
                    reason="bam_id oracle missing — run dump_bam_id.R")
def test_bam_id_by_factor_matches_mgcv():
    """s(x2, by=fac, id=1): every by-level block shares ONE λ (full.sp repeats
    sp[0] across the three blocks) + an unlinked s(x0) carries its own. sp/edf/
    scale pin to mgcv-bam: the by-factor sweep-drop constraint (sparse.cons=-1)
    is applied to the SHARED pre-by basis once, then × the level dummy
    (smooth.r:3947-3991) — matching mgcv (plan item P20). Previously hea derived
    it per masked level, so the sparsest level's edf was ~70% high."""
    df = pl.read_csv(str(_BAM_ID / "byfac" / "data.csv")).with_columns(
        pl.col("fac").cast(pl.Enum(["f1", "f2", "f3"])))
    m = hea.models.bam("y ~ fac + s(x2, by=fac, id=1) + s(x0)", df,
                       method="REML")
    meta = _id_meta("byfac")
    sp_ref = _id_col("byfac", "sp.csv")
    fsp_ref = _id_col("byfac", "full_sp.csv")
    stable = _id_stable("byfac")
    assert len(m.sp) == 2 and len(m._slots) == 4
    np.testing.assert_allclose(
        np.exp(m._rho_hat), [m.sp[0], m.sp[0], m.sp[0], m.sp[1]], rtol=1e-12)
    np.testing.assert_allclose(np.exp(m._rho_hat), fsp_ref, rtol=1e-4)
    np.testing.assert_allclose(m.sp, sp_ref, rtol=1e-4)
    np.testing.assert_allclose(m.sigma_squared, meta["scale"], rtol=1e-5)
    for lbl, edf in m.edf_by_smooth.items():
        np.testing.assert_allclose(edf, stable[lbl], rtol=1e-4)


def test_bam_id_fixed_sp_takes_working_length():
    """sp= supplies the *working* parameters (mgcv semantics): one value drives
    both linked penalties. Length must be n_work (=1), not n_slots (=2)."""
    d = _bam_id_data()
    m = hea.models.bam("y ~ s(x0, id=1) + s(x1, id=1)", d, sp=[2.0])
    assert len(m.sp) == 1 and len(m._slots) == 2
    np.testing.assert_allclose(np.exp(m._rho_hat), [2.0, 2.0], rtol=1e-12)
    with pytest.raises(ValueError, match="length 1"):
        hea.models.bam("y ~ s(x0, id=1) + s(x1, id=1)", d, sp=[2.0, 3.0])


def test_bam_id_singleton_is_noop():
    """An id used by a single smooth links nothing — same model as no id."""
    d = _bam_id_data()
    m1 = hea.models.bam("y ~ s(x0, id=9) + s(x1)", d, method="REML")
    m0 = hea.models.bam("y ~ s(x0) + s(x1)", d, method="REML")
    assert len(m1.sp) == 2
    np.testing.assert_allclose(m1.sp, m0.sp, rtol=1e-9)
    np.testing.assert_allclose(m1.REML_criterion, m0.REML_criterion, rtol=1e-12)


# =============================================================================
# 8. scale-unknown non-Gaussian φ-estimation cadence (plan item P19)
# =============================================================================
# A scale-unknown non-Gaussian bam (Gamma, inverse Gaussian, fixed-p Tweedie,
# the extended families) estimates φ jointly with the sp's. hea used to run the
# converge-fully _outer_newton on each frozen (R, f) linearisation — minimising
# the WORKING-RSS REML, whose (ρ, φ) optimum differs from the RESPONSE-deviance
# optimum mgcv reaches by ONE POI step + re-linearise per PIRLS iter. The gap
# was large (Gamma sp 0.158 vs mgcv-bam 0.205 = 3.7×; Tweedie 0.207 vs 0.259).
# bam now routes these through the same one-step POI cadence, so sp/scale/edf/
# fitted pin to mgcv-**bam** (φ≡1 families keep the outer-Newton path — they
# already matched). NB this is genuine bam↔gam divergence: mgcv-gam Gamma sp is
# 0.579, mgcv-bam 0.205 — bam's reduced-(R,f) cadence is a different estimator.
# Oracle: tests/r_oracle/dump_bam_estscale.R → tests/fixtures/bam_estscale/.
_BAM_ES = Path(__file__).parent / "fixtures" / "bam_estscale"


@pytest.mark.skipif(not (_BAM_ES / "tweedie" / "meta.csv").exists(),
                    reason="bam_estscale oracle missing — run dump_bam_estscale.R")
@pytest.mark.parametrize("case, fam_factory", [
    ("tweedie", lambda: __import__("hea.family", fromlist=["Tweedie"]).Tweedie(p=1.4)),
    ("gamma", lambda: __import__("hea.family", fromlist=["Gamma"]).Gamma(link="log")),
])
def test_bam_estscale_phi_matches_mgcv_bam(case, fam_factory):
    """Scale-unknown non-Gaussian bam pins sp/scale/edf/fitted to mgcv-bam via
    the POI one-step φ-estimation cadence (P19). sp is an argmin/inverse-Hessian
    quantity → BLAS flat-optimum band (rtol 1e-4); the well-determined fit
    quantities (scale, edf, fitted μ̂) pin tighter."""
    df = pl.read_csv(str(_BAM_ES / case / "data.csv"))
    with open(_BAM_ES / case / "meta.csv", newline="") as f:
        meta = {k: float(v) for k, v in next(csv.DictReader(f)).items()}
    fit_ref = np.array(
        [float(x) for x in (_BAM_ES / case / "fitted.csv").read_text().split()])
    m = hea.models.bam("y ~ z + s(x, k=12)", df, family=fam_factory(),
                       method="REML")
    np.testing.assert_allclose(m.sp[0], meta["sp"], rtol=1e-4)
    np.testing.assert_allclose(m.sigma_squared, meta["scale"], rtol=1e-4)
    np.testing.assert_allclose(m.edf_total, meta["edf_total"], rtol=1e-4)
    np.testing.assert_allclose(m.fitted_values, fit_ref, rtol=1e-4, atol=1e-6)
