"""hea.ggplot — Grammar of Graphics in Python (a port of R's ggplot2).

This is the *package*; the :func:`ggplot` factory function lives inside
it. Use ``from hea.ggplot import ggplot, aes, geom_point`` rather than
``from hea import ggplot`` (the latter binds the package, not the function).

Phase 0+ surface: ``ggplot``, ``aes``, ``geom_point``, ``geom_blank``,
``geom_bar``/``geom_col``/``geom_histogram``, ``geom_density``, plus the
underlying ``stat_*`` family. Subsequent phases land continuous scales,
polar coords (the strategic piece — see
``.claude/plans/ggplot2-port.md``), facets, themes, guides, and
circular-statistics extensions in :mod:`hea.ggplot.circular`.
"""

from __future__ import annotations

from .aes import aes, after_scale, after_stat
from .core import ggplot
from .facets import facet_wrap
from .theme import (
    element_blank,
    element_line,
    element_rect,
    element_text,
    theme,
    theme_bw,
    theme_classic,
    theme_dark,
    theme_gray,
    theme_minimal,
    theme_void,
)
from .geoms import (
    geom_area,
    geom_bar,
    geom_blank,
    geom_boxplot,
    geom_col,
    geom_density,
    geom_histogram,
    geom_jitter,
    geom_line,
    geom_path,
    geom_point,
    geom_ribbon,
    geom_smooth,
    geom_step,
    geom_text,
    geom_violin,
)
from .positions import (
    position_dodge,
    position_dodge2,
    position_fill,
    position_identity,
    position_jitter,
    position_nudge,
    position_stack,
)
from .scales import (
    scale_alpha,
    scale_alpha_continuous,
    scale_alpha_manual,
    scale_color_brewer,
    scale_color_continuous,
    scale_color_distiller,
    scale_color_gradient,
    scale_color_gradient2,
    scale_color_gradientn,
    scale_color_identity,
    scale_color_manual,
    scale_color_viridis_c,
    scale_color_viridis_d,
    scale_colour_brewer,
    scale_colour_continuous,
    scale_colour_distiller,
    scale_colour_gradient,
    scale_colour_gradient2,
    scale_colour_gradientn,
    scale_colour_identity,
    scale_colour_manual,
    scale_colour_viridis_c,
    scale_colour_viridis_d,
    scale_fill_brewer,
    scale_fill_continuous,
    scale_fill_distiller,
    scale_fill_gradient,
    scale_fill_gradient2,
    scale_fill_gradientn,
    scale_fill_identity,
    scale_fill_manual,
    scale_fill_viridis_c,
    scale_fill_viridis_d,
    scale_linetype,
    scale_linetype_manual,
    scale_shape,
    scale_shape_manual,
    scale_size,
    scale_size_area,
    scale_size_continuous,
    scale_size_manual,
    scale_x_continuous,
    scale_x_log10,
    scale_x_log2,
    scale_x_reverse,
    scale_x_sqrt,
    scale_y_continuous,
    scale_y_log10,
    scale_y_log2,
    scale_y_reverse,
    scale_y_sqrt,
)
from .stats import (
    stat_bin,
    stat_boxplot,
    stat_count,
    stat_density,
    stat_identity,
    stat_smooth,
    stat_ydensity,
)

__all__ = [
    "ggplot",
    "aes",
    "after_stat",
    "after_scale",
    "geom_blank",
    "geom_point",
    "geom_jitter",
    "geom_bar",
    "geom_col",
    "geom_histogram",
    "geom_density",
    "geom_line",
    "geom_path",
    "geom_step",
    "geom_ribbon",
    "geom_area",
    "geom_smooth",
    "geom_boxplot",
    "geom_violin",
    "geom_text",
    "stat_identity",
    "stat_bin",
    "stat_count",
    "stat_density",
    "stat_smooth",
    "stat_boxplot",
    "stat_ydensity",
    "scale_x_continuous",
    "scale_y_continuous",
    "scale_x_log10",
    "scale_y_log10",
    "scale_x_log2",
    "scale_y_log2",
    "scale_x_sqrt",
    "scale_y_sqrt",
    "scale_x_reverse",
    "scale_y_reverse",
    "scale_color_manual",
    "scale_colour_manual",
    "scale_fill_manual",
    "scale_color_identity",
    "scale_colour_identity",
    "scale_fill_identity",
    "scale_color_continuous",
    "scale_colour_continuous",
    "scale_fill_continuous",
    "scale_color_gradient",
    "scale_colour_gradient",
    "scale_fill_gradient",
    "scale_color_gradient2",
    "scale_colour_gradient2",
    "scale_fill_gradient2",
    "scale_color_gradientn",
    "scale_colour_gradientn",
    "scale_fill_gradientn",
    "scale_color_viridis_c",
    "scale_colour_viridis_c",
    "scale_fill_viridis_c",
    "scale_color_viridis_d",
    "scale_colour_viridis_d",
    "scale_fill_viridis_d",
    "scale_color_brewer",
    "scale_colour_brewer",
    "scale_fill_brewer",
    "scale_color_distiller",
    "scale_colour_distiller",
    "scale_fill_distiller",
    "scale_size",
    "scale_size_continuous",
    "scale_size_area",
    "scale_size_manual",
    "scale_alpha",
    "scale_alpha_continuous",
    "scale_alpha_manual",
    "scale_shape",
    "scale_shape_manual",
    "scale_linetype",
    "scale_linetype_manual",
    "facet_wrap",
    "theme",
    "theme_gray",
    "theme_bw",
    "theme_minimal",
    "theme_classic",
    "theme_void",
    "theme_dark",
    "element_text",
    "element_line",
    "element_rect",
    "element_blank",
    "position_identity",
    "position_jitter",
    "position_nudge",
    "position_dodge",
    "position_dodge2",
    "position_stack",
    "position_fill",
]
