"""Type stubs for the compiled ``hea._rs`` extension (Rust crate ``hea-rs``, via
PyO3). Built from ``rust/`` by maturin. Absent on sdist / no-toolchain installs —
callers degrade to the pure-Python ``hea.R.nmath`` kernels (see
``hea/R/_dispatch.py``). All kernels take/return 1-D float64 arrays (Python
pre-broadcasts to equal length); trailing flags are bools.
"""
import numpy as np
from numpy.typing import NDArray

_A = NDArray[np.float64]

# normal (mu/sigma are arrays, uniform with the rest of the surface)
def pnorm(x: _A, mu: _A, sigma: _A, lower_tail: bool = ..., log_p: bool = ...) -> _A: ...
def qnorm(p: _A, mu: _A, sigma: _A, lower_tail: bool = ..., log_p: bool = ...) -> _A: ...
def dnorm(x: _A, mu: _A, sigma: _A, give_log: bool = ...) -> _A: ...

# gamma function / Loader saddlepoint kernels
def lgammafn(x: _A) -> _A: ...
def gammafn(x: _A) -> _A: ...
def stirlerr(n: _A) -> _A: ...
def bd0(x: _A, np_: _A) -> _A: ...
def pow1p(x: _A, y: _A) -> _A: ...
def dpois_raw(x: _A, lam: _A, give_log: bool = ...) -> _A: ...
def dbinom_raw(x: _A, n: _A, p: _A, q: _A, give_log: bool = ...) -> _A: ...

# gamma family
def pgamma(x: _A, alph: _A, scale: _A, lower_tail: bool = ..., log_p: bool = ...) -> _A: ...
def dgamma(x: _A, shape: _A, scale: _A, give_log: bool = ...) -> _A: ...
def qgamma(p: _A, alpha: _A, scale: _A, lower_tail: bool = ..., log_p: bool = ...) -> _A: ...

# beta (toms708)
def pbeta(x: _A, a: _A, b: _A, lower_tail: bool = ..., log_p: bool = ...) -> _A: ...
def lbeta(a: _A, b: _A) -> _A: ...
def qbeta(alpha: _A, p: _A, q: _A, lower_tail: bool = ..., log_p: bool = ...) -> _A: ...

# discrete
def ppois(x: _A, lam: _A, lower_tail: bool = ..., log_p: bool = ...) -> _A: ...
def dpois(x: _A, lam: _A, give_log: bool = ...) -> _A: ...
def qpois(p: _A, lam: _A, lower_tail: bool = ..., log_p: bool = ...) -> _A: ...
def pbinom(x: _A, n: _A, p: _A, lower_tail: bool = ..., log_p: bool = ...) -> _A: ...
def dbinom(x: _A, n: _A, p: _A, give_log: bool = ...) -> _A: ...
def qbinom(p: _A, n: _A, pr: _A, lower_tail: bool = ..., log_p: bool = ...) -> _A: ...
def dbeta(x: _A, a: _A, b: _A, give_log: bool = ...) -> _A: ...

# t / F
def pt(x: _A, n: _A, lower_tail: bool = ..., log_p: bool = ...) -> _A: ...
def qt(p: _A, ndf: _A, lower_tail: bool = ..., log_p: bool = ...) -> _A: ...
def dt(x: _A, n: _A, give_log: bool = ...) -> _A: ...
def pf(x: _A, df1: _A, df2: _A, lower_tail: bool = ..., log_p: bool = ...) -> _A: ...
def qf(p: _A, df1: _A, df2: _A, lower_tail: bool = ..., log_p: bool = ...) -> _A: ...

# exponential
def dexp(x: _A, scale: _A, give_log: bool = ...) -> _A: ...
def pexp(x: _A, scale: _A, lower_tail: bool = ..., log_p: bool = ...) -> _A: ...
def qexp(p: _A, scale: _A, lower_tail: bool = ..., log_p: bool = ...) -> _A: ...
